src/hotspot/share/runtime/globals_ext.hpp

Summary: Ported from Dragonwell 8
Test Plan: build and sanity test
Reviewed-by: kuaiwei
Issue: #1

[Misc] Added Dragonwell 11 VM args extension

---

src/hotspot/share/services/attachListener.cpp
src/hotspot/share/services/diagnosticCommand.cpp
src/hotspot/share/services/diagnosticCommand.hpp
src/hotspot/share/services/heapDumper.cpp
src/hotspot/share/services/heapDumper.hpp
src/jdk.jcmd/share/classes/sun/tools/jmap/JMap.java
test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniDump.sh
test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniHeapDumpOpts.sh
test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestNoMinidumpAtFullGC.java

Summary: port mini-heapdump feature to Dragonwell 11
Test Plan: test/jdk/tools, test/hotspot/serviceability
Reviewed-by: kuaiwei
Issue: #5

[Misc] Port mini-heapdump to Dragonwell 11

---

README.md

Summary: Update README.md to remove installation approaches unavailable for now
Test Plan: N/A
Reviewed-by: sanhong
Issue: #9

[Misc] Update README.md by removing installation approaches unavailable for now

---

.github/workflows/check_pr.yml

Summary: Added following checks:
- Commit format checking, using dragonwell-releng/check_commit_action@master.
- Build and run sanity test in release and slowdebug mode.
Test Plan: checks shipped with this PR
Reviewed-by: yuleil, kuaiwei
Issue: #11

[Misc] Added workflow to check each pull request

---

.github/workflows/check_pr.yml
make.sh
src/hotspot/share/gc/shared/allocTracer.inline.hpp

Summary: fix some misc things to build fastdebug version dragonwell11
Test Plan: build Dragonwell in fastdebug mode
Reviewed-by: luchsh,sanhong,D-D-H
Issue: https://github.com/alibaba/dragonwell11/issues/13

[Misc] Solve fastdebug build issues

---

make.sh

Summary:
Update dragonwell11 version to 11.0.7.2
Reviewers: luchsh, D-D-H
Bug: https://github.com/alibaba/dragonwell11/issues/20

[Misc] Update dragonwell version to 11.0.7.2

---

make/autoconf/hotspot.m4
src/hotspot/cpu/aarch64/aarch64.ad
src/hotspot/cpu/aarch64/c1_LIRAssembler_aarch64.cpp
src/hotspot/cpu/aarch64/gc/z/zBarrierSetAssembler_aarch64.cpp
src/hotspot/cpu/aarch64/gc/z/zBarrierSetAssembler_aarch64.hpp
src/hotspot/cpu/aarch64/gc/z/z_aarch64.ad
src/hotspot/cpu/aarch64/stubGenerator_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zArguments_linux_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zBackingFile_linux_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zBackingFile_linux_aarch64.hpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zBackingPath_linux_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zBackingPath_linux_aarch64.hpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zGlobals_linux_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zGlobals_linux_aarch64.hpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zPhysicalMemoryBacking_linux_aarch64.cpp
src/hotspot/os_cpu/linux_aarch64/gc/z/zPhysicalMemoryBacking_linux_aarch64.hpp

Issue: https://github.com/alibaba/dragonwell11/issues/89

[Backport] ZGC for Aarch64

---

src/hotspot/share/gc/shared/gc_globals.hpp
src/hotspot/share/gc/z/z_globals.hpp
src/hotspot/share/jfr/metadata/metadata.xml
test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java
test/hotspot/jtreg/compiler/loopopts/TestRangeCheckPredicatesControl.java
test/hotspot/jtreg/gc/arguments/TestDisableDefaultGC.java
test/hotspot/jtreg/gc/stress/gcbasher/TestGCBasherWithZ.java
test/hotspot/jtreg/gc/stress/gcold/TestGCOldWithZ.java
test/hotspot/jtreg/gc/z/TestAlwaysPreTouch.java
test/hotspot/jtreg/gc/z/TestHighUsage.java
test/hotspot/jtreg/gc/z/TestSmallHeap.java
test/hotspot/jtreg/gc/z/TestUncommit.java
test/jdk/java/lang/management/MemoryMXBean/MemoryTestZGC.sh
test/jdk/jdk/jfr/event/gc/detailed/TestZAllocationStallEvent.java
test/jdk/jdk/jfr/event/gc/detailed/TestZPageAllocationEvent.java
test/jdk/jdk/jfr/event/gc/detailed/TestZRelocationSetEvent.java
test/jdk/jdk/jfr/event/gc/detailed/TestZRelocationSetGroupEvent.java
test/jdk/jdk/jfr/event/gc/detailed/TestZUncommitEvent.java

Summary: Turn ZGC-related flags into product
Reviewed-by: mmyxym, linade
Test Plan: hotspot_gc and tier1 with ZGC
Issue: https://github.com/alibaba/dragonwell11/pull/125

[GC] Turn ZGC-related flags into product

---

test/jdk/com/alibaba/wisp/monitor/TestPassToken.java

Summary: There is an unlocked time window between pass token and
notify next, causing the test to occasionally fail.
Test Plan: TestPassToken
Reviewed-by: D-D-H, joeylee97
Issue: alibaba/dragonwell11#204

[Wisp] Fix TestPassToken

---

.github/workflows/submit.yml
test/hotspot/jtreg/ProblemList.txt
test/hotspot/jtreg/TEST.groups
test/hotspot/jtreg/runtime/coroutine/testPremainWithWispMonitor.sh
test/jdk/ProblemList.txt
test/jdk/TEST.groups

Summary: Enable tests for Dragonwell related groups.
Reviewed-by: yuleil, Accelerator1996
Test Plan: github action
Issue: https://github.com/alibaba/dragonwell11/issues/192

[Misc] Enable action for Dragonwell features

---

src/java.base/linux/classes/com/alibaba/wisp/engine/WispEngine.java
src/java.base/linux/classes/com/alibaba/wisp/engine/WispTask.java
src/java.base/linux/classes/com/alibaba/wisp/engine/WispThreadWrapper.java
src/java.base/macosx/classes/com/alibaba/wisp/engine/WispEngine.java
src/java.base/share/classes/java/lang/Thread.java
src/java.base/share/classes/jdk/internal/misc/WispEngineAccess.java
src/java.base/windows/classes/com/alibaba/wisp/engine/WispEngine.java
src/java.management/share/classes/sun/management/ThreadImpl.java
src/java.management/share/classes/sun/management/WispThreadCompositeData.java
test/jdk/com/alibaba/wisp/thread/TestThreadInfo.java
test/jdk/com/alibaba/wisp/thread/TestThreadState.java

Summary: Support Thread.getState() and ThreadMxBean
Test Plan: jtreg jdk/com/alibaba/wisp
Reviewed-by: yuleil, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell11/issues/175

[Wisp] Support thread state and ThreadMxbean

---

src/hotspot/share/jfr/dcmd/jfrDcmds.cpp
src/hotspot/share/jfr/dcmd/jfrDcmds.hpp
src/hotspot/share/jfr/recorder/service/jfrOptionSet.cpp
src/jdk.jfr/share/classes/jdk/jfr/internal/dcmd/DCmdConfigure.java
test/jdk/jdk/jfr/startupargs/TestOptionsWithLocale.java

Summary: Backport 8244508 to fix locale problem caused by JFR
Test Plan: jtreg jdk/jfr
Reviewed-by: lingjun-cg, yanglong1010
Issue: https://github.com/alibaba/dragonwell11/issues/243

[Backport] 8244508: JFR: FlightRecorderOptions reset date format

---

test/jdk/com/sun/jdi/TestScaffold.java

Summary: fix testcase bug test/jdk/com/sun/jdi/StepTest.java, for addClassExclusionFilter("com.alibaba.*")
Reviewed-by: lei.yul, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/252

[Misc] fix testcase bug StepTest.java

---

.github/workflows/submit.yml

Summary: enable ci test on branch VectorAPI_dev
Reviewed-by: lei.yul, sendaoYan
Issue: https://github.com/alibaba/dragonwell11/issues/249

[Misc] Enable VectorAPI_dev github action

---

test/jdk/tools/launcher/Test7029048.java

Summary: fix testcase bug test/jdk/tools/launcher/Test7029048.java,
duplicated method definition, it's introduced by merging upstream's alpine
support.
Reviewed-by: lei.yul, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/261

[Misc] fix testcase bug Test7029048.java

---

.github/workflows/check_pr.yml
.github/workflows/submit.yml

Summary: fix github action and add arm64 build in workflow
Reviewed-by: lvfei.lv, lei.yul
Issue: https://github.com/alibaba/dragonwell11/issues/341

[Misc] fix github action and add arm64 build in workflow

---

.github/workflows/submit.yml
make/conf/test-dependencies
test/hotspot/jtreg/ProblemList.txt

Summary: add arm64 build and test in workflow
Reviewed-by: sendaoYan, lei.yul
Issue: https://github.com/alibaba/dragonwell11/issues/341

[Misc] add arm64 build and test in workflow

---

test/jdk/com/alibaba/wisp/io/WispFileIOTest.java
test/jdk/com/alibaba/wisp/thread/TestThreadInfo.java
test/jdk/java/dyn/TestBasicSteal.java
test/jdk/java/dyn/TestConcurrentSteal.java
test/jdk/java/dyn/TestCoroutine.java

Summary: Fix tests
Test Plan: test/jdk/java/dyn
Reviewed-by: D-D-H, yuleil
Issue: #405

[Wisp] Fix test/jdk/java/dyn tests

---

src/java.base/share/classes/com/alibaba/util/Utils.java
src/java.base/share/classes/java/lang/ClassLoader.java
src/java.base/share/classes/jdk/internal/misc/JavaLangClassLoaderAccess.java
src/java.base/share/classes/jdk/internal/misc/SharedSecrets.java
src/java.base/share/classes/module-info.java

Summary: A ClassLoader instance signature mechanism. With this, we can distinguish unique named ClassLoader instances.
Test Plan: tests are inside future patches
Issue: #402

[Misc] Introduce a ClassLoader instance signature mechanism

---

src/hotspot/cpu/x86/x86.ad
src/hotspot/share/opto/compile.cpp
src/hotspot/share/opto/vectornode.cpp
test/hotspot/jtreg/compiler/vectorization/TestMacroLogicVector.java

[Backport] 8250745, 8242491, 8244186
Summary: 8250745, 8242491, 8244186
Issue: https://github.com/alibaba/dragonwell11/issues/412
https://github.com/alibaba/dragonwell11/issues/413
https://github.com/alibaba/dragonwell11/issues/414

[Backport] 8250745, 8242491, 8244186

---

src/hotspot/cpu/x86/x86.ad

[Backport] 8255210, 8255378
Summary: Backport 8255210, 8255378
Issue: #434 #436

[Backport] 8255210, 8255378

---

src/hotspot/cpu/x86/c2_MacroAssembler_x86.cpp
src/hotspot/cpu/x86/x86.ad
src/hotspot/share/opto/vector.cpp

[Backport] 8256054, 8255448
Summary: [Backport] 8256054, 8255448
Issue: #439 #442

[Backport] 8256054, 8255448

---

src/hotspot/share/prims/vectorSupport.cpp
src/hotspot/share/prims/vectorSupport.hpp

Summary: [Backport] 8256073: Improve vector rematerialization support
Issue: https://github.com/alibaba/dragonwell11/issues/447

[Backport] 8256073: Improve vector rematerialization support

---

src/hotspot/cpu/x86/x86.ad
src/jdk.incubator.vector/share/classes/jdk/incubator/vector/DoubleVector.java
src/jdk.incubator.vector/share/classes/jdk/incubator/vector/FloatVector.java
src/jdk.incubator.vector/share/classes/jdk/incubator/vector/X-Vector.java.template

Summary: [Backport] 8256995: [vector] Improve broadcast operations
Issue: https://github.com/alibaba/dragonwell11/issues/451

[Backport] 8256995: [vector] Improve broadcast operations

---

src/hotspot/share/opto/vectorIntrinsics.cpp
src/hotspot/share/opto/vectornode.cpp

Summary: [Backport] 8258989, 8259353
Issue: #459 #460

[Backport] 8258989, 8259353

---

src/hotspot/cpu/x86/macroAssembler_x86.cpp
src/hotspot/cpu/x86/macroAssembler_x86.hpp
src/hotspot/cpu/x86/x86.ad
src/hotspot/share/opto/memnode.cpp
src/hotspot/share/opto/vectorIntrinsics.cpp
test/hotspot/jtreg/compiler/arraycopy/TestArrayCopyMaskedWithZeroSrc.java
test/hotspot/jtreg/compiler/vectorapi/TestVectorShuffleIotaByte.java
test/hotspot/jtreg/compiler/vectorapi/VectorReinterpretTest.java
test/hotspot/jtreg/compiler/vectorization/TestMemoryVectorMismatched.java
test/jdk/jdk/incubator/vector/AddTest.java

Summary: [Backport] 8258272,8259775,8263972,8255915,8265956
Issue: #461 #462 #466 #467 #464

[Backport] 8258272,8259775,8263972,8255915,8265956

---

src/hotspot/share/opto/vectorIntrinsics.cpp
src/hotspot/share/opto/vectornode.cpp
src/hotspot/share/opto/vectornode.hpp

Summary: [Backport] 8257625: C2: Harden input checks in vector intrinsics
Issue: https://github.com/alibaba/dragonwell11/issues/453

[Backport] 8257625: C2: Harden input checks in vector intrinsics

---

make/copy/Copy-java.base.gmk
make/hotspot/symbols/symbols-unix
src/hotspot/share/classfile/systemDictionary.hpp
src/hotspot/share/classfile/vmSymbols.hpp
src/hotspot/share/include/jvm.h
src/hotspot/share/logging/logTag.hpp
src/hotspot/share/memory/metaspaceShared.cpp
src/hotspot/share/prims/jvm.cpp
src/hotspot/share/runtime/arguments.cpp
src/hotspot/share/runtime/arguments.hpp
src/hotspot/share/runtime/quickStart.cpp
src/hotspot/share/runtime/quickStart.hpp
src/hotspot/share/runtime/thread.cpp
src/hotspot/share/services/diagnosticCommand.cpp
src/hotspot/share/services/diagnosticCommand.hpp
src/java.base/share/classes/com/alibaba/cds/CDSDumperHelper.java
src/java.base/share/classes/com/alibaba/util/CDSDumpHook.java
src/java.base/share/classes/com/alibaba/util/QuickStart.java
src/java.base/share/conf/quickstart.properties
src/java.base/share/native/libjava/QuickStart.c

Summary: A framework to help Java users reduce Java applications' startup speed. Currently use EagerAppCDS as its feature.
Test Plan: tested internally; tests are inside future patches.
Issue: #345

[QuickStart] QuickStart implementation

---

test/jdk/com/alibaba/quickstart/Config.java
test/jdk/com/alibaba/quickstart/LoadMultiVersionedJarClass.java
test/jdk/com/alibaba/quickstart/MyWebAppClassLoader.java
test/jdk/com/alibaba/quickstart/ProfileDumpTestRunner.java
test/jdk/com/alibaba/quickstart/QuickStartFeature.java
test/jdk/com/alibaba/quickstart/SourceConstants.java
test/jdk/com/alibaba/quickstart/TestAllFeaturePlainJarProfileDump.java
test/jdk/com/alibaba/quickstart/TestAssemblyFiles.java
test/jdk/com/alibaba/quickstart/TestDeterminingTracerOrReplayer.java
test/jdk/com/alibaba/quickstart/TestDump.java
test/jdk/com/alibaba/quickstart/TestEagerAppCDSPlainJarProfileDump.java
test/jdk/com/alibaba/quickstart/TestEagerAppCDSWithParametersProfileDump.java
test/jdk/com/alibaba/quickstart/TestForceReplayer.java
test/jdk/com/alibaba/quickstart/TestIntegrityCheck.java
test/jdk/com/alibaba/quickstart/TestMultiVersionedJar.java
test/jdk/com/alibaba/quickstart/TestNotifyDump.java
test/jdk/com/alibaba/quickstart/TestNotifyDumpByAPI.java
test/jdk/com/alibaba/quickstart/TestNotifyDumpByJcmd.java
test/jdk/com/alibaba/quickstart/TestParallelProcessRun.java
test/jdk/com/alibaba/quickstart/TestPrintStat.java
test/jdk/com/alibaba/quickstart/TestQuickStartOptions.java
test/jdk/com/alibaba/quickstart/TrivialArrayUtil.java

Summary: Tests for quickstart
Test Plan: test/jdk/com/alibaba/quickstart
Issue: #345

[QuickStart] Add Quickstart tests

---

src/hotspot/cpu/x86/assembler_x86.cpp
src/hotspot/cpu/x86/vm_version_ext_x86.cpp
src/hotspot/cpu/x86/vm_version_x86.cpp
src/hotspot/cpu/x86/vm_version_x86.hpp

Summary: Add Hygon Dhyana processor support
Test Plan: Verify in production environment
Reviewed-by: D-D-H, zhengxiaolinX
Issue: #516

[Backport] 8222090: Add Hygon Dhyana processor support

---

src/hotspot/share/gc/g1/g1CollectedHeap.cpp
src/hotspot/share/gc/g1/g1CollectedHeap.hpp
src/hotspot/share/gc/g1/g1CollectedHeap.inline.hpp
src/hotspot/share/gc/g1/g1ConcurrentMark.cpp
src/hotspot/share/gc/g1/g1Policy.cpp
src/hotspot/share/gc/g1/g1RemSet.cpp
src/hotspot/share/gc/g1/g1YoungRemSetSamplingThread.cpp
src/hotspot/share/gc/g1/g1YoungRemSetSamplingThread.hpp
src/hotspot/share/gc/g1/g1_globals.hpp
src/hotspot/share/gc/g1/heapRegionManager.cpp
src/hotspot/share/gc/g1/heapRegionManager.hpp
src/hotspot/share/gc/g1/heapRegionManager.inline.hpp
src/hotspot/share/gc/g1/heapRegionRemSet.cpp
src/hotspot/share/gc/g1/heapRegionRemSet.hpp
src/hotspot/share/gc/g1/vm_operations_g1.cpp
src/hotspot/share/gc/g1/vm_operations_g1.hpp
src/hotspot/share/gc/shared/gcCause.cpp
src/hotspot/share/gc/shared/gcCause.hpp
src/hotspot/share/gc/shared/vmGCOperations.cpp
src/hotspot/share/logging/logTag.hpp
src/hotspot/share/services/writeableFlags.cpp
src/hotspot/share/services/writeableFlags.hpp
test/hotspot/jtreg/gc/g1/TestPeriodicCollection.java
test/hotspot/jtreg/gc/g1/TestPeriodicCollectionJNI.java
test/hotspot/jtreg/gc/g1/TestPeriodicLogMessages.java
test/hotspot/jtreg/gc/g1/humongousObjects/objectGraphTest/TestObjectGraphAfterGC.java
test/hotspot/jtreg/gc/g1/libTestPeriodicCollectionJNI.c

Summary: Backport JEP346 Promptly Return Unused Committed Memory from G1
Test Plan: jtreg/gc/g1
Reviewed-by: mmyxym, linade
Issue: https://github.com/dragonwell-project/dragonwell11/issues/662

[GC] Backport JEP346 Promptly Return Unused Committed Memory from G1

---

.github/workflows/submit.yml

Summary: Fix CI workflow
Test Plan: CI
Reviewed-by: sendaoYan, yuleil
Issue: https://github.com/dragonwell-project/dragonwell11/issues/674

[Misc] Fix CI workflow

---

src/hotspot/share/gc/g1/g1CollectedHeap.cpp
src/hotspot/share/gc/g1/g1FullCollector.cpp
src/hotspot/share/gc/g1/g1FullGCAdjustTask.cpp
src/hotspot/share/gc/g1/g1FullGCAdjustTask.hpp
src/hotspot/share/gc/g1/g1FullGCCompactTask.cpp
src/hotspot/share/gc/g1/g1FullGCCompactTask.hpp
src/hotspot/share/gc/g1/g1FullGCCompactionPoint.cpp
src/hotspot/share/gc/g1/g1FullGCCompactionPoint.hpp
src/hotspot/share/gc/g1/g1FullGCOopClosures.hpp
src/hotspot/share/gc/g1/g1FullGCOopClosures.inline.hpp
src/hotspot/share/gc/g1/g1FullGCPrepareTask.cpp
src/hotspot/share/gc/g1/g1FullGCPrepareTask.hpp
src/hotspot/share/gc/shared/gc_globals.hpp
src/hotspot/share/gc/shared/preservedMarks.cpp
src/hotspot/share/gc/shared/preservedMarks.hpp
src/hotspot/share/gc/shared/slidingForwarding.cpp
src/hotspot/share/gc/shared/slidingForwarding.hpp
src/hotspot/share/gc/shared/slidingForwarding.inline.hpp
src/hotspot/share/oops/markOop.hpp
src/hotspot/share/utilities/fastHash.hpp
test/hotspot/jtreg/gc/stress/systemgc/TestSystemGCWithG1.java
test/hotspot/jtreg/gc/stress/systemgc/TestSystemGCWithParallel.java

Summary: Introduce UseAltGCForwarding to support alternative full GC forwarding.
Now support G1 and parallelGC. The code accords to 8305896 and https://github.com/openjdk/lilliput-jdk17u/
Reviewed-by: yude.lin, yifeng.jin
Issue: https://github.com/dragonwell-project/dragonwell11/issues/683

[Backport] 8305896: Alternative full GC forwarding

---

.github/commit_message_template

Summary: This patch updates dragweonll standard commit template accordingly
Testing: local
Reviewers: Accelerator1996, sanhong
Issue: https://github.com/dragonwell-project/dragonwell11/issues/724

[Misc] Update dragonwell standard commit template

---

test/hotspot/jtreg/runtime/appcds/TestCommon.java

Summary: as title
Testing: test/hotspot/jtreg/runtime/appcds/TestCommon.java
Reviewers: lingjun-cg, yulei
Issue:

[EagerAppCDS] fix merge conflicts

---

src/hotspot/share/runtime/globals.hpp

[JIT] Change option UseVtableBasedCHA to product
Summary: Change option UseVtableBasedCHA to be product from diagnostic
Testing: jtreg
Reviewers: zhuoren.wz, maoliang.ml
Issue: https://github.com/dragonwell-project/dragonwell11/issues/774

[JIT] Change option UseVtableBasedCHA to product

---

src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp

[GC] Fix & optimize arrayEquals on AArch64 (#743)
Summary: fix tail comparison and simplify flow control for arrayEquals
Testing: jdk/javadoc/tool/parser/7091528/T7091528.java
Reviewers: mmyxym, linade
Issue: https://github.com/dragonwell-project/dragonwell11/issues/743

[GC] Fix & optimize arrayEquals on AArch64 (#743)

---

test/hotspot/jtreg/compiler/codecache/stress/CodecacheMemoryCheck.sh
test/hotspot/jtreg/compiler/codecache/stress/CodecacheMemoryCheckPress.sh
test/hotspot/jtreg/compiler/codecache/stress/UnexpectedDeoptimizationTestLoop.java
test/hotspot/jtreg/compiler/codecache/stress/get-native-memory-usage.pl
test/hotspot/jtreg/compiler/codecache/stress/plot.gp

Summary: Add presess testcase for mem leak of ReduceNMethodSize
Reviewers: JoshuaZhuwj, kuaiwei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/861

[JIT] Add presess testcase for mem leak of ReduceNMethodSize

---

test/jdk/java/nio/channels/DatagramChannel/StressNativeSignal.java

Summary: Backport JDK-8327650 to fix java/nio/channels/DatagramChannel/StressNativeSignal.java intermittent fails
Reviewers: Accelerator1996, ziyilin
Issue: https://github.com/dragonwell-project/dragonwell11/issues/908

[Misc] Backport JDK-8327650 to fix StressNativeSignal.java intermittent fails

---

test/jdk/com/alibaba/wisp/TestIo.java

Summary: as title
Testing: test/jdk/com/alibaba/wisp/TestIo.java
Reviewers: yulei.lx, lusou.zq
Issue: https://github.com/dragonwell-project/dragonwell11/issues/925

[Wisp] improve NIO testcase for wisp

---

src/hotspot/share/ci/ciCallProfile.hpp
src/hotspot/share/ci/ciMethod.cpp
src/hotspot/share/opto/doCall.cpp
src/hotspot/share/runtime/arguments.cpp
src/hotspot/share/runtime/deoptimization.cpp
src/hotspot/share/runtime/deoptimization.hpp
src/hotspot/share/runtime/globals_ext.hpp
test/hotspot/jtreg/compiler/inlining/TestPolymorphicInlining.java

Summary: inline and devirtualize more receivers in polymorphic conditions
Testing: jtreg and ci
Reviewers: maoliang, Kuaiwei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/917

[JIT] enable polymorphic inlining and devirtualization
