dragonwell-project/dragonwell11

src/hotspot/share/gc/shared/memAllocator.cpp, src/hotspot/share/gc/shared/memAllocator.hpp, src/hotspot/share/runtime/globals_ext.hpp, test/hotspot/jtreg/runtime/memory/TestArrayAllocationWarning.java
Summary:
ported from Dragonwell 8, added new flag ArrayAllocationWarningSize
to warn allocation of large arrays
Test Plan: test/hotspot/jtreg/runtime/memory
Reviewed-by: kuaiwei
Issue: #3
=> [Runtime] Added large array allocation warning

src/jdk.jfr/share/conf/jfr/default.jfc, src/jdk.jfr/share/conf/jfr/profile.jfc
Summary: add missing configuration to default/profile.jfc
Test Plan: test/jdk/jdk/jfr
Reviewed-by: tbzhang, luchsh
Issue: https://github.com/alibaba/dragonwell11/issues/18
=> [JFR] Some test failure caused by opto object allocations sampling

src/hotspot/share/gc/shared/allocTracer.cpp, src/hotspot/share/jfr/objectprofiler/objectProfiler.cpp, src/hotspot/share/jfr/objectprofiler/objectProfiler.hpp
Summary:
Dragonwell can not build on windows without precompiled header due
to dragonwell JFR commit 3471dab85033c97085cce3b731b70d455ce908c2
Reviewed-by: D-D-H,zhengxiaolinX
Test Plan: run build on adopt pipeline
Issue: https://github.com/alibaba/dragonwell11/issues/25
=> [Misc] Fix build error on windows due to no precompiled header

src/hotspot/os/linux/osContainer_linux.cpp
Summary: Fix a warning reported by GCC9. Dragonwell can be compiled by
GCC9 after this patch.
Reviewed-by: joeyleeeeeee97, Wei Kuai
Test Plan: build test
Issue: https://github.com/alibaba/dragonwell11/issues/27
=> [Misc] fix a warning reported by GCC9

src/hotspot/share/gc/shared/allocTracer.hpp, src/hotspot/share/gc/shared/allocTracer.inline.hpp, src/hotspot/share/utilities/macros.hpp
Summary: add two macros NOT_JFR_RETURN/NOT_JFR_RETURN_(also exist in
upstream)
Reviewed-by: kuaiwei, kelthuzadx
Test Plan: minimal build
Issue: https://github.com/alibaba/dragonwell11/issues/65
=> [Misc] Fix minimal build error caused by JFR

make/hotspot/gensrc/GensrcAdlc.gmk, src/hotspot/cpu/x86/gc/z/zBarrierSetAssembler_x86.cpp, src/hotspot/cpu/x86/gc/z/zBarrierSetAssembler_x86.hpp, src/hotspot/cpu/x86/gc/z/z_x86_64.ad, src/hotspot/cpu/x86/x86_64.ad, src/hotspot/os_cpu/linux_x86/gc/z/zArguments_linux_x86.cpp, src/hotspot/share/gc/z/zArguments.cpp, src/hotspot/share/gc/z/zForwardingTable.cpp, src/hotspot/share/gc/z/zForwardingTableEntry.hpp, src/hotspot/share/gc/z/zObjectAllocator.cpp, src/hotspot/share/gc/z/zReferenceProcessor.cpp, src/hotspot/share/gc/z/zReferenceProcessor.hpp, src/hotspot/share/gc/z/zRuntimeWorkers.cpp, src/hotspot/share/gc/z/zThread.cpp, src/hotspot/share/gc/z/zThread.hpp, src/hotspot/share/gc/z/zWorkers.cpp, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/tools/JMap.java, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/utilities/HeapHprofBinWriter.java, test/hotspot/jtreg/serviceability/sa/TestJmapCore.java
8214377: ZGC: Don't use memset to initialize array of ZForwardingTableEntry
8215487: ZGC: ZRuntimeWorkers incorrectly identify themselves as ZWorkers
8215985: ZGC: Simplify reference processing in light of JDK-8175797
8215547: ZGC: Fix incorrect match rule for loadBarrierWeakSlowRegNoVec
8217856: ZGC: Break out C2 matching rules into separate AD file
8216385: ZGC: Fix building without C2
8216372: ZGC: Put C2 load barrier stub routines in separate codeblobs
8213323: sa/TestJmapCoreMetaspace.java and sa/TestJmapCore.java fail with ZGC
8217258: ZGC: Minor cleanup of ZBarrierSetAssembler
@sandlerwang please review 8215547 by verifying if VectorAPI or other parts of JVM will be influenced since `rxmm`s are changed
@mmyxym @linade @leveretconey please review the patches that mention your id …
=> Merge [GC] Minor optimization of ZBarrierSetAssembler, ZReferenceProcess, ZForwardingTableEntry, etc. 

src/hotspot/share/gc/z/c2/zBarrierSetC2.cpp, src/hotspot/share/gc/z/c2/zBarrierSetC2.hpp, src/hotspot/share/opto/compile.cpp, src/hotspot/share/opto/escape.cpp, src/hotspot/share/opto/escape.hpp, src/hotspot/share/opto/matcher.cpp
I am splitting #89 into three pull requests.
1. 8213615: GC/C2 abstraction for escape analysis (only ZGC part)
2. 8217503: ZGC: Fix fall through bug in ZBarrierSetC2::escape_add_final_edges()
3. 8213489: GC/C2 abstraction for Compile::final_graph_reshaping() (ZGC-only)
4. 8213746: GC/C2 abstraction for C2 matcher **(introduced in Apr.26)**
1-3 have been ported in #92.
You can only review 4 (8213746) since 1-3 were cleanly cherry-picked.
=> [Backport] [GC] Backport GC interface for ZGC

src/hotspot/share/gc/z/zDirector.cpp, src/hotspot/share/gc/z/z_globals.hpp, test/hotspot/jtreg/gc/z/TestHighUsage.java
Summary: Introduce option -XX:ZHighUsagePercent
- The option sets the percentage of heap usage for ZGC High Usage rule
- The option sets a decimal number (95.0 by default, which does not
change the behavior of the original High Usage rule)
Test Plan: gc/z/TestHighUsage.java
Reviewers: weixlu, mmyxym
Issue: https://github.com/alibaba/dragonwell11/pull/114
The original patch is from https://code.aone.alibaba-inc.com/xcode/jdk11/commit/9e2d3b12d00d96e3f5c4ba91164af5e6c6f541b5
=> [GC] ZGC: Make "High Usage" threshold adjustable

src/hotspot/os/posix/os_posix.cpp, src/hotspot/os/posix/os_posix.hpp, src/hotspot/share/gc/z/zLock.hpp, src/hotspot/share/gc/z/zLock.inline.hpp
Summary: Compilation error due to clock_gettime().
Backport os::PlatformMonitor, the original Monitor implementation for
ZConditionLock. Relavent JDK patches:
* 8210832: https://github.com/openjdk/jdk/commit/c94cdddbdd
* 8246265: https://github.com/openjdk/jdk/commit/cd16b568ce
Test Plan: gc/z/
Reviewed-by: linade, weixlu
Issue: https://github.com/alibaba/dragonwell11/pull/115
=> [GC] Backport 8210832 for ZGC ZConditionLock

src/java.base/share/classes/java/io/ClassResolveCache.java, src/java.base/share/classes/java/io/ObjectInputStream.java, test/jdk/java/io/ObjectInputStream/PeekInputStreamTest.java, test/jdk/java/io/ObjectInputStream/ResolveProxyClass.java, test/jdk/java/io/ObjectInputStream/TestObjectStreamClass.java, test/micro/com/alibaba/bench/java/io/ObjectInputStreamTest.java
Summary:
Introduce fast serialization feature.
This feature can be enabled by -Dcom.alibaba.enableFastSerialization=true.
1. Create a ClassResolveCache to reduce calls to Class.forName(String)
2. Cache latestUserDefinedLoader(): The loader can be safely cached inside
the ObjectInputStream class, once custom readObject() methods are invoked,
the cache will be invalid.
For simple data objects, we can observe a 26% performance improvement.
See com.alibaba.bench.java.io.ObjectInputStreamTest.
Reviewed-by: joeyleeeeeee97, sandlerwang, sanhong
Test Plan:
Add one more round for ObjectInputStream jtreg test with
-Dcom.alibaba.enableFastSerialization=true
Issue: #118
=> [Misc] Fast serialization

src/hotspot/share/gc/z/zHeuristics.cpp, src/hotspot/share/gc/z/z_globals.hpp
Summary: Reserve more space for ZGC relocation to avoid OOM.
Test Plan: gc/z/
Issue: https://github.com/alibaba/dragonwell11/pull/117
=> [GC] Add ZRelocationReserve to reserve more space for ZGC relocation

src/hotspot/share/gc/z/zHeuristics.cpp, src/hotspot/share/gc/z/z_globals.hpp
Summary: Adjust the upper bound of the object size in medium pages.
Test Plan: hotspot_gc and tier1 with ZGC
Issue: https://github.com/alibaba/dragonwell11/pull/116
=> [GC] Add option ZMediumObjectUpperBound for ZGC

src/java.base/share/classes/java/io/ObjectInputStream.java, src/java.base/share/classes/java/io/ResolvedClassCache.java
Summary:
Give a more meaningful name to the class cache in fast serialization
feature.
Reviewed-by: D-D-H, joeyleeeeeee97
Test Plan: run ObjectInputStream jtregs
Issue: #118
=> [Misc] rename ClassResolveCache to ResolvedClassCache

test/hotspot/jtreg/gc/testlibrary/Allocation.java, test/hotspot/jtreg/gc/z/TestSmallHeap.java
Summary: ZGC JFR tests are using gc.testlibrary.Allocation.blackHole
instead of java.lang.ref.Reference.reachabilityFence (JDK-8235250).
JDK-8235250: https://github.com/openjdk/jdk/commit/c023983c7f
Reviewed-by: linade, weixlu
Test Plan: jdk/jdk/jfr/event/gc/detailed/, hotspot/jtreg/gc/z/
Issue: https://github.com/alibaba/dragonwell11/pull/126
=> [GC] Backport gc.testlibrary.Allocation.blackHole for ZGC JFR tests

src/hotspot/share/gc/z/zBarrierSet.cpp, src/hotspot/share/gc/z/zHeap.cpp, src/hotspot/share/gc/z/zMark.cpp, src/hotspot/share/gc/z/zRootsIterator.cpp, src/hotspot/share/gc/z/zRootsIterator.hpp, src/hotspot/share/gc/z/zUnload.cpp
(1) Fix incorrect `do_class_loader_data_graph` by applying `always_strong_cld_do`
(2) forcely trigger unloading if cause == system_gc
(3) Debug build failed when ZGC is unloading classes. `ZHeap::heap()` is NULL at this point.
=> [GC] Fix an assertion failure on ZGC class unloading

src/hotspot/share/gc/z/zMark.cpp, src/hotspot/share/gc/z/zNMethodTable.cpp, src/hotspot/share/gc/z/zNMethodTable.hpp, src/hotspot/share/gc/z/zRootsIterator.cpp, src/hotspot/share/gc/z/zRootsIterator.hpp, test/hotspot/jtreg/gc/z/unloading/TestUnloadFrequency.java
Summary: "Verify oop store failed" if an immediate value of a nmethod is accessed,
because the corresponding nmethod entry barrier is not disarmed properly.
Test Plan: jtreg/gc/z/unloading/TestUnloading.java
Issue: https://github.com/alibaba/dragonwell11/issues/177
=> [GC] Disarm all nmethods if the ZGC cycle does not unload classes

src/hotspot/share/gc/z/zDriver.cpp
Summary: So far GC MXBean fails to report the pause time of ZGC class unloading. We report the pause time in this patch.
Reviewed-by: mmyxym, albert.th
Test Plan: jtreg/gc/z/
Issue: https://github.com/alibaba/dragonwell11/issues/180
=> [GC] MXBean should report the pause time of class unloading

src/hotspot/share/gc/z/zHeap.cpp, test/hotspot/jtreg/gc/z/unloading/TestUnloadFrequency.java, test/hotspot/jtreg/gc/z/unloading/TestUnloadGarbageCollectorMXBean.java
Summary: Add a test to check ZGC MXBean reports pause time of
class unloading
Reviewed-by: albert.th, mmyxym
Test Plan: gc/z/
Issue: https://github.com/alibaba/dragonwell11/pull/181
=> [GC] Add test for pause time record of ZGC class unloading

src/hotspot/share/jfr/recorder/checkpoint/types/jfrTypeSet.cpp
Summary: use 0 as size value for primitive types
Test Plan: all JFR related test cases
Reviewed-by: leveretconey, kelthuzadx
Issue: https://github.com/alibaba/dragonwell11/pull/188
=> [JFR] Fix JFR related test cases caused by merging 11.0.13

src/hotspot/share/jfr/jni/jfrJniMethod.cpp, src/hotspot/share/jfr/leakprofiler/sampling/objectSampler.cpp, src/hotspot/share/jfr/recorder/jfrEventSetting.cpp, src/hotspot/share/jfr/recorder/jfrEventSetting.hpp, src/hotspot/share/jfr/recorder/service/jfrEvent.hpp, src/hotspot/share/jfr/recorder/stacktrace/jfrStackTrace.cpp, src/hotspot/share/jfr/recorder/stacktrace/jfrStackTrace.hpp, src/hotspot/share/jfr/recorder/stacktrace/jfrStackTraceRepository.cpp, src/hotspot/share/jfr/recorder/stacktrace/jfrStackTraceRepository.hpp, src/hotspot/share/jfr/support/jfrFlush.cpp, src/hotspot/share/jfr/support/jfrFlush.hpp, src/hotspot/share/jfr/support/jfrStackTraceMark.cpp, src/hotspot/share/jfr/support/jfrThreadLocal.cpp, src/hotspot/share/jfr/support/jfrThreadLocal.hpp, src/hotspot/share/opto/macro.cpp, src/hotspot/share/opto/runtime.cpp, src/hotspot/share/opto/runtime.hpp, src/hotspot/share/prims/jvm.cpp, src/hotspot/share/runtime/vframe.hpp, test/jdk/jdk/jfr/event/objectsprofiling/TestOptoObjectAllocationsSampling.java
Hi,
Please help review this patch that fixes the stack trace problem of object profiling on the aarch64 platform.
The root cause of this problem is that the stack layout of aarch64 is different from x86_64 so that we cannot use vframeStream(thread, os::current_frame()) to get the java call stack traces.
This fix uses CallStaticJavaNode to invoke the jfr_fast_object_alloc_C so that the _last_Java_pc is set properly by opto stub.
Issue: https://github.com/alibaba/dragonwell11/issues/189
Denghui
=> [JFR] Fix object profiling stacktrace problem on aarch64 platform

README.md
Summary: Add publications 'Towards a Serverless Java Runtime (ASE'21)' and 'Platinum: A CPU-Efficient Concurrent Garbage Collector for Tail-Reduction of Interactive Services (ATC'20)'; also change the format.
Test Plan: -
Reviewers: tianxiaogu, sanhong
Issue: https://github.com/alibaba/dragonwell11/issues/136
=> [Misc] Update publications in README.md

src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp
Summary: Backport JDK-8248048 to avoid C2 SIGILL.
https://github.com/openjdk/jdk/commit/a18e8d3d5710
Reviewed-by: weixlu, mmyxym
Test Plan: test/jdk/java/util/concurrent/forkjoin/Integrate.java with ZGC
Issue: https://github.com/alibaba/dragonwell11/pull/196
=> [GC] 8248048: ZGC: AArch64: SIGILL in load barrier register spilling

test/jdk/com/alibaba/wisp/TestWispCounter.java, test/jdk/com/alibaba/wisp/TestWispDetailCounter.java, test/jdk/com/alibaba/wisp/TestWispMonitorData.java, test/jdk/com/alibaba/wisp/io/TestCreateFdOnDemand.java
Summary: Use unbound port to avoid confliction.
Reviewed-by: yuleil, kelthuzadx
Test Plan: jtreg wisp
Issue: https://github.com/alibaba/dragonwell11/issues/192
=> [Misc] fix unstable wisp tests

src/hotspot/cpu/riscv/assembler_riscv.hpp, src/hotspot/cpu/riscv/globals_riscv.hpp, src/hotspot/cpu/riscv/macroAssembler_riscv.cpp, src/hotspot/cpu/riscv/macroAssembler_riscv.hpp, src/hotspot/cpu/riscv/nativeInst_riscv.cpp, src/hotspot/cpu/riscv/nativeInst_riscv.hpp, src/hotspot/cpu/riscv/riscv.ad
Summary:
add UseCSky option to enable csky instructions
merge ld/st into paired memory instructions
Test Plan: SPECjbb2005
Reviewed-by: zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell11/issues/216
CR: https://github.com/alibaba/dragonwell11/pull/217
=> [RISCV] support paired memory instruction in CSky

.github/workflows/submit.yml, src/hotspot/share/gc/shared/taskqueue.hpp
Summary: Make parent class ParallelTaskTerminator destructor virtual.
Test Plan: Test case
Reviewed-by:
Issue: https://github.com/alibaba/dragonwell11/issues/220
=> [GC] Memory leak because OWSTTaskTerminator destructor not called

src/hotspot/share/gc/g1/g1CollectedHeap.cpp, src/hotspot/share/gc/g1/g1ParScanThreadState.cpp, src/hotspot/share/gc/g1/g1ParScanThreadState.hpp, src/hotspot/share/gc/g1/g1Policy.cpp, src/hotspot/share/gc/g1/g1Policy.hpp
Summary: Backport of 8228609 with adjustment for 8227442.
Test Plan: Local test case
Issue: https://github.com/alibaba/dragonwell11/issues/226
=> [GC] 8228609: G1 copy cost prediction uses used vs. actual copied bytes

src/jdk.jfr/share/classes/jdk/jfr/internal/dcmd/DCmdStart.java, test/jdk/jdk/jfr/event/objectsprofiling/TestOptionIsDisabled.java, test/jdk/jdk/jfr/event/objectsprofiling/testsettings.jfc
Summary: Should use the logic like DCmdStart#hasJDKEvents to determine
if an event is enabled or not
Test Plan: jdk/jfr/event/objectsprofiling/TestOptionIsDisabled.java
Reviewed-by: yanglong1010, kelthuzadx
Issue: https://github.com/alibaba/dragonwell11/issues/237
=> [JFR] Unexpected behavior when enable Opto related allocation event by JCMD when -XX:FlightRecorderOptions=sampleobjectallocations=true is disabled

src/hotspot/share/gc/z/zArguments.cpp, src/hotspot/share/gc/z/z_globals.hpp, test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java
Summary: ZUnmapBadViews has been removed in
https://github.com/alibaba/dragonwell11/commit/39f759e977 .
In order to be compatible with Java 11, ZUnmapBadViews must be
supported. To achieve compatibility, This patch makes ZUnmapBadViews
indentical with ZVerifyViews.
Reviewed-by: mmyxym, linade
Test Plan: test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java
Issue: https://github.com/alibaba/dragonwell11/pull/240
=> [GC] Restore option ZUnmapBadViews

test/hotspot/jtreg/gc/z/TestSoftMaxHeapSizeFlag.java
Reviewed-by: tanghaoth90,joeyleeeeeee97
Summary: fix testcase TestSoftMaxHeapSizeFlag.java run error for error package name
Test Plan: test/hotspot/jtreg/gc/z/TestSoftMaxHeapSizeFlag.java
Issue: #223
Signed-off-by: sendaoYan yansendao.ysd@alibaba-inc.com
=> [Misc]: fix testcase TestSoftMaxHeapSizeFlag.java run error

make/autoconf/jdk-version.m4
Summary: supports white spaces in vendor-version-string
Reviewed-by: lei.yul, sendaoYan
Issue: https://github.com/alibaba/dragonwell11/issues/246
=> [Misc] Supports white spaces in vendor-version-string

src/hotspot/share/runtime/coroutine.cpp, src/hotspot/share/runtime/coroutine.hpp, src/hotspot/share/runtime/thread.cpp, src/hotspot/share/runtime/thread.hpp
Summary: Wisp unfortunately missed doing do_oop() for WispThread, which is corresponded to a Coroutine data structure. We shall add it.
Test Plan: all wisp tests
Reviewed-by: yuleil, sanhong
Issue: #263
=> [Wisp] Fix missing oops_do for WispThread

src/hotspot/cpu/x86/x86_32.ad, src/hotspot/cpu/x86/x86_64.ad, src/hotspot/share/adlc/archDesc.cpp
[Backport] 8234387: C2: Better support of operands with multiple match rules in AD files
Summary: Backport VectorAPI 8234387: C2: Better support of operands with multiple match rules in AD files
Issue: https://github.com/alibaba/dragonwell11/issues/268
=> [Backport] 8234387: C2: Better support of operands with multiple match rules in AD files

src/hotspot/share/adlc/adlparse.cpp, src/hotspot/share/adlc/archDesc.cpp, src/hotspot/share/adlc/formsopt.cpp, src/hotspot/share/adlc/formsopt.hpp, src/hotspot/share/adlc/output_c.cpp
[Backport] 8234394: C2: Dynamic register class support in ADLC
Summary: Backport VectorAPI 8234394: C2: Dynamic register class support in ADLC
Issue: https://github.com/alibaba/dragonwell11/issues/269
=> [Backport] 8234394: C2: Dynamic register class support in ADLC

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/arm/arm.ad, src/hotspot/cpu/ppc/ppc.ad, src/hotspot/cpu/s390/s390.ad, src/hotspot/cpu/sparc/sparc.ad, src/hotspot/cpu/x86/x86.ad, src/hotspot/cpu/x86/x86_32.ad, src/hotspot/cpu/x86/x86_64.ad, src/hotspot/share/adlc/output_h.cpp, src/hotspot/share/opto/compile.cpp, src/hotspot/share/opto/machnode.cpp, src/hotspot/share/opto/machnode.hpp, src/hotspot/share/opto/matcher.cpp, src/hotspot/share/opto/matcher.hpp, src/hotspot/share/opto/phase.cpp, src/hotspot/share/opto/phase.hpp
[Backport] 8234391 C2: Generic vector operands & 8234392 C2: Extend Matcher::match_rule_supported_vector() with element type information
Summary: Backport VectorAPI 8234391 C2: Generic vector operands & 8234392 C2: Extend Matcher::match_rule_supported_vector() with element type information. Merge 8234391 & 8234392
Issue: https://github.com/alibaba/dragonwell11/issues/277
=> [Backport] 8234391 C2: Generic vector operands & 8234392 C2: Extend Matcher::match_rule_supported_vector() with element type information

src/hotspot/cpu/x86/x86.ad
[Backport] 8235405: C2: Merge AD instructions for different vector operations
Summary: Backport VectorAPI 8235405: C2: Merge AD instructions for different vector operations
Issue: https://github.com/alibaba/dragonwell11/issues/282
=> [Backport] 8235405: C2: Merge AD instructions for different vector operations

src/hotspot/cpu/x86/x86.ad
[Backport] 8235824: C2: Merge AD instructions for AddReductionV and MulReductionV nodes
Summary: Backport VectorAPI 8235824: C2: Merge AD instructions for AddReductionV and MulReductionV nodes
Issue: https://github.com/alibaba/dragonwell11/issues/284
=> [Backport] 8235824: C2: Merge AD instructions for AddReductionV and MulReductionV nodes

src/hotspot/cpu/x86/macroAssembler_x86.cpp, src/hotspot/cpu/x86/macroAssembler_x86.hpp, src/hotspot/cpu/x86/x86.ad
[Backport] 8235719: C2: Merge AD instructions for ShiftV, AbsV, and NegV nodes
Summary: Backport VectorAPI 8235719: C2: Merge AD instructions for ShiftV, AbsV, and NegV nodes
Issue: https://github.com/alibaba/dragonwell11/issues/287
=> [Backport] 8235719: C2: Merge AD instructions for ShiftV, AbsV, and NegV nodes

src/hotspot/cpu/x86/x86.ad
[Backport] 8235688: C2: Merge AD instructions for AddV, SubV, and MulV nodes
Summary: Backport VectorAPI 8235688: C2: Merge AD instructions for AddV, SubV, and MulV nodes
Issue: https://github.com/alibaba/dragonwell11/issues/290
=> [Backport] 8235688: C2: Merge AD instructions for AddV, SubV, and MulV nodes

src/hotspot/cpu/x86/x86.ad
[Backport] 8235825: C2: Merge AD instructions for Replicate nodes
Summary: Backport VectorAPI 8235825: C2: Merge AD instructions for Replicate nodes. vector_length(), vector_length_in_bytes() and vector_length_encoding() merged ahead to pass the build.
Issue: https://github.com/alibaba/dragonwell11/issues/286
=> [Backport] 8235825: C2: Merge AD instructions for Replicate nodes

src/hotspot/cpu/x86/x86.ad
[Backport] 8235756: C2: Merge AD instructions for DivV, SqrtV, and FmaV nodes
Summary: Backport VectorAPI 8235756: C2: Merge AD instructions for DivV, SqrtV, and FmaV nodes
Issue: https://github.com/alibaba/dragonwell11/issues/292
=> [Backport] 8235756: C2: Merge AD instructions for DivV, SqrtV, and FmaV nodes

test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java
Summary: fix test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java run OOM on same machine
Reviewed-by: lei.yul, qingfeng.yy
Issue: https://github.com/alibaba/dragonwell11/issues/267
=> [Misc] fix UnsafeIntrinsicsTest.java run OOM on same machine

make/hotspot/gensrc/GensrcAdlc.gmk, src/hotspot/cpu/riscv/assembler_riscv.hpp, src/hotspot/cpu/riscv/c1_LIRAssembler_riscv.cpp, src/hotspot/cpu/riscv/c1_globals_riscv.hpp, src/hotspot/cpu/riscv/globals_riscv.hpp, src/hotspot/cpu/riscv/macroAssembler_riscv.cpp, src/hotspot/cpu/riscv/macroAssembler_riscv.hpp, src/hotspot/cpu/riscv/register_riscv.hpp, src/hotspot/cpu/riscv/riscv.ad, src/hotspot/cpu/riscv/riscv_v.ad, src/hotspot/cpu/riscv/stubGenerator_riscv.cpp, src/hotspot/cpu/riscv/vm_version_riscv.cpp, src/hotspot/cpu/riscv/vm_version_riscv.hpp, src/hotspot/os_cpu/linux_riscv/os_linux_riscv.cpp, src/hotspot/share/opto/matcher.cpp, src/hotspot/share/opto/matcher.hpp
We can enable the vector extension on real boards after this adaptation.
=> [RISCV] Backport RVV and support RVV-0.7.1

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/arm/arm.ad, src/hotspot/cpu/ppc/ppc.ad, src/hotspot/cpu/s390/s390.ad, src/hotspot/cpu/sparc/sparc.ad, src/hotspot/cpu/x86/x86.ad, src/hotspot/share/opto/matcher.cpp, src/hotspot/share/opto/matcher.hpp
[Backport] VectorAPI: 8236364: TEMP vector registers could be incorrectly assigned upper bank xmm registers after Generic Operands (JDK-8234391)
Summary: Backport VectorAPI 8236364: TEMP vector registers could be incorrectly assigned upper bank xmm registers after Generic Operands (JDK-8234391)
Issue: https://github.com/alibaba/dragonwell11/issues/300
=> [Backport] VectorAPI: 8236364: TEMP vector registers could be incorrectly assigned upper bank xmm registers after Generic Operands (JDK-8234391)

src/hotspot/share/opto/matcher.cpp, src/hotspot/share/opto/matcher.hpp, src/hotspot/share/opto/vectornode.cpp, src/hotspot/share/opto/vectornode.hpp
[Backport] VectorAPI: 8236443: Issues with specializing vector register type for phi operand with generic operands
Summary: Fix special handling for operand resolution of vectorshift and shiftcount nodes. Fix for crash in the resolution algorithm due to non-machine type nodes.
Issue: https://github.com/alibaba/dragonwell11/issues/302
=> [Backport] VectorAPI: 8236443: Issues with specializing vector register type for phi operand with generic operands

src/hotspot/share/c1/c1_LIRGenerator.cpp, test/jdk/com/alibaba/wisp/monitor/deopt/TestSynchronizedMethodC1Crash.java
Summary: MonitorExit introduces new 'State' to generate OopMaps and Debuginfo, yet dead locals on the 'State' doesn't get cleaned. We need to clean them because all locals are dead after the implicit monitorexit.
Test Plan: deopt/TestSynchronizedMethodC1Crash.java, which can reproduce this issue.
Reviewed-by: leiyul, sandlerwang, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/216
=> [Wisp] C1: Clear dead locals for MonitorExit that copies state to generate debuginfo

src/java.base/linux/classes/com/alibaba/wisp/engine/TaskDispatcher.java, src/java.base/linux/classes/com/alibaba/wisp/engine/ThreadAsWisp.java, src/java.base/linux/classes/com/alibaba/wisp/engine/WispCarrier.java, src/java.base/linux/classes/com/alibaba/wisp/engine/WispEngine.java, src/java.base/linux/classes/com/alibaba/wisp/engine/WispTask.java, src/java.base/macosx/classes/com/alibaba/wisp/engine/WispEngine.java, src/java.base/share/classes/java/lang/Thread.java, src/java.base/share/classes/jdk/internal/misc/WispEngineAccess.java, src/java.base/windows/classes/com/alibaba/wisp/engine/WispEngine.java, test/jdk/com/alibaba/wisp2/Wisp2StackSizeTest.java
Summary:
Previously wisp uses 512k as the stack size and ignores Thread.stackSize. This PR will make wisp to use Thread.stackSize as its stack size. Cherry-pick https://github.com/alibaba/dragonwell8/commit/e64b3fc40856483466e67e39b70ffcc938b74c64.
Test Plan: jtreg:com/jdk/alibaba/wisp2/
Reviewed-by: yuleil, zhengxiaolinX
=> [Wisp] Adapt `Thread.stackSize`

src/java.base/linux/classes/com/alibaba/wisp/engine/WispEngine.java, src/java.base/macosx/classes/com/alibaba/wisp/engine/WispEngine.java, src/java.base/share/classes/java/nio/channels/spi/AbstractSelectableChannel.java, src/java.base/share/classes/jdk/internal/misc/WispEngineAccess.java, src/java.base/share/classes/sun/nio/ch/IOStatus.java, src/java.base/share/classes/sun/nio/ch/ServerSocketChannelImpl.java, src/java.base/share/classes/sun/nio/ch/SocketChannelImpl.java, src/java.base/unix/classes/sun/nio/ch/SinkChannelImpl.java, src/java.base/unix/classes/sun/nio/ch/SourceChannelImpl.java, src/java.base/windows/classes/com/alibaba/wisp/engine/WispEngine.java, test/jdk/com/alibaba/wisp/io/TestBlockingNIO.java
Summary: Hook blocking entry at pipeChannel and SocketChannel,
current WispTask would block itself to wait for next scheduling.
Test Plan: jtreg TestBlockIngIO.
Reviewed-by: zhengxiaolinX, ddh
Issue: alibaba/dragonwell11#272
=> [Wisp] Blocking io support for SocketChannel and Pipe

test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniDump.sh, test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniHeapDumpOpts.sh
Summary: fix TestMiniDump.sh intermittently does not terminate java process when test finish, especially test run fail
Reviewed-by: albert.th, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/306
=> [Misc] fix TestMiniDump.sh intermittently does not terminate java process when test finish

test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniHeapDumpOpts.sh
Summary: fix error get PID method in test/hotspot/jtreg/serviceability/sa/jmap-minidump/TestMiniHeapDumpOpts.sh and enable it
Reviewed-by: albert.th, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/308
=> [Misc] fix error get PID method in TestMiniHeapDumpOpts.sh and enable it

test/jdk/com/alibaba/wisp/io/TestBlockingAccept2.java
Summary: fix port conflict between com/alibaba/wisp/io/TestBlockingAccept2.java and com/alibaba/wisp/io/TestBlockingNIO.java
Reviewed-by: yunyao.zxl, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/310
=> [Misc] fix port conflict between TestBlockingAccept2.java and TestBlockingAccept2.java

test/jdk/com/alibaba/wisp2/exclusive/bug/TestPreemptWisp2InternalBug.java
Summary: fix com/alibaba/wisp2/exclusive/bug/TestPreemptWisp2InternalBug.java intermittently fail, run 4 times in a test, if 2 times or more can not match the expect message, then the test is fail.
Reviewed-by: yunyao.zxl, lei.yul
Issue: https://github.com/alibaba/dragonwell11/issues/313
=> [Misc] fix TestPreemptWisp2InternalBug.java intermittently fail

test/jdk/sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java
Summary: fix sun/security/provider/SecureRandom/AbstractDrbg/SpecTest.java intermittently fail, use /dev/urandom instead of /dev/random to avoid block for SecureRandom API
Reviewed-by: lvfei.lv, lei.yul
Issue: https://github.com/alibaba/dragonwell11/issues/322
=> [Misc] fix SpecTest.java intermittently timeout

test/jdk/java/security/cert/CertPathBuilder/targetConstraints/BuildEEBasicConstraints.java, test/jdk/java/security/cert/pkix/policyChanges/TestPolicy.java
Summary: fix TestPolicy.java and BuildEEBasicConstraints.java fail because of certificates expired
Reviewed-by: lvfei.lv, lei.yul
Issue: https://github.com/alibaba/dragonwell11/issues/327
=> [Misc] fix TestPolicy.java and BuildEEBasicConstraints.java fail because of certificates expired

test/hotspot/jtreg/ProblemList.txt, test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java
Summary: fix test/hotspot/jtreg/compiler/gcbarriers/UnsafeIntrinsicsTest.java run OOM on same machine, and revert commit 9e37ea4aa6ebd5eb7510d08c957b6c8d577bb890
Reviewed-by: kuaiwei.kw, lvfei.lv
Issue: https://github.com/alibaba/dragonwell11/issues/267
=> [Misc] fix UnsafeIntrinsicsTest.java run OOM on same machine and revert commit 9e37ea4aa6ebd5eb7510d08c957b6c8d577bb890

src/java.management/share/classes/sun/management/WispThreadCompositeData.java
Summary: WispThreadCompositeData.getCompositeData() uses LockSupport.getBlocker(), which would throw NPE to break its process.
Test Plan: com/alibaba/wisp/thread/TestThreadInfo.java
Reviewed-by: D-D-H, lvfei
Issue: #345
=> [Wisp] WispThreadCompositeData.getCompositeData() should handle null WispTask

test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java
Summary: Fix a test to pass the GHA checks.
Test Plan: test/hotspot/jtreg/compiler/floatingpoint/TestLibmIntrinsics.java
Reviewed-by: kuaiwei
Issue: #209
=> [Misc] Fix ported TestLibmIntrinsics.java

src/hotspot/share/asm/assembler.hpp, src/hotspot/share/asm/codeBuffer.hpp
[Backport] 8241042: x86_64: Improve Assembler generation. 
Summary: 8241042: x86_64: Improve Assembler generation.  src/hotspot/cpu/x86/assembler_x86.cpp not included, only src/hotspot/share/asm/assembler.hpp and src/hotspot/share/asm/codeBuffer.hpp, for VectorAPI backport.
Test Plan: ci jtreg    
Issue: #351
=> [Backport] 8241042: x86_64: Improve Assembler generation. 

src/java.management/share/classes/sun/management/ThreadImpl.java, src/java.management/share/classes/sun/management/WispThreadCompositeData.java
Summary: sun.management.ThreadInfoCompositeData.threadState() will use valueOf() to read Thread.State String. We should specify a TERMINATED String for it. Also, a cleanup.
Test Plan: com/alibaba/wisp/thread/TestThreadInfo.java
Reviewed-by: D-D-H, yuleil
Issue: #345
=> [Wisp] WispThreadCompositeData.getCompositeData() should use legal Thread State String

src/hotspot/share/jvmci/jvmciCompilerToVM.cpp, src/hotspot/share/runtime/deoptimization.cpp, src/hotspot/share/runtime/deoptimization.hpp
Summary: Subset of 8223320: [AOT] jck test api/javax_script/ScriptEngine/PutGet.html fails when test classes are AOTed. For VectorAPI: 8223347.
Issue: https://github.com/alibaba/dragonwell11/issues/361
=> [Backport] Subset of 8223320 for VectorAPI: 8223347

src/hotspot/cpu/x86/assembler_x86.cpp, src/hotspot/cpu/x86/assembler_x86.hpp, src/hotspot/cpu/x86/x86.ad
[Backport] 8238680: C2: Remove redundant AD instructions for Replicate nodes
Summary: Backport 8238680: C2: Remove redundant AD instructions for Replicate nodes
Issue: https://github.com/alibaba/dragonwell11/issues/363
=> [Backport] 8238680: C2: Remove redundant AD instructions for Replicate nodes

src/hotspot/cpu/x86/assembler_x86.cpp, src/hotspot/cpu/x86/x86.ad
[Backport] 8239008: C2: Simplify Replicate support for sub-word types on x86
Summary: Backport 8239008: C2: Simplify Replicate support for sub-word types on x86
Issue: https://github.com/alibaba/dragonwell11/issues/365
=> [Backport] 8239008: C2: Simplify Replicate support for sub-word types on x86

src/hotspot/cpu/x86/x86_32.ad
Summary: Backport 8242073: x86_32 build failure after JDK-8241040
Issue: https://github.com/alibaba/dragonwell11/issues/369
=> [Backport] 8242073: x86_32 build failure after JDK-8241040

src/hotspot/cpu/x86/assembler_x86.cpp, src/hotspot/cpu/x86/assembler_x86.hpp
[Backport] 8241434: x86: Fix Assembler::emit_operand asserts for XMM registers
Summary: Backport 8241434: x86: Fix Assembler::emit_operand asserts for XMM registers
Issue: https://github.com/alibaba/dragonwell11/issues/374
=> [Backport] 8241434: x86: Fix Assembler::emit_operand asserts for XMM registers

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/arm/arm.ad, src/hotspot/cpu/ppc/ppc.ad, src/hotspot/cpu/s390/s390.ad, src/hotspot/cpu/sparc/sparc.ad, src/hotspot/cpu/x86/x86.ad, src/hotspot/share/opto/matcher.cpp, src/hotspot/share/opto/matcher.hpp, src/hotspot/share/opto/vectornode.hpp
Summary: Backport 8242492: C2: Remove Matcher::vector_shift_count_ideal_reg()
Issue: https://github.com/alibaba/dragonwell11/issues/352
=> [Backport] 8242492: C2: Remove Matcher::vector_shift_count_ideal_reg()

src/hotspot/cpu/x86/x86.ad
[Backport] 8239009: C2: Don't use PSHUF to load scalars from memory on x86
Summary: Backport 8239009: C2: Don't use PSHUF to load scalars from memory on x86
Issue: https://github.com/alibaba/dragonwell11/issues/381
=> [Backport] 8239009: C2: Don't use PSHUF to load scalars from memory on x86

src/java.base/linux/classes/com/alibaba/wisp/engine/WispConfiguration.java, src/java.base/linux/classes/com/alibaba/wisp/engine/WispEventPump.java, test/jdk/com/alibaba/wisp2/bug/TestIssue311.java
Summary: Supports different coroutines waiting on the same socket's read and write events. Solve a wisp bug triggered by okhttp.
Test Plan: TestIssue311
Reviewed-by: zhengxiaolinX, D-D-H
Issue: [#311](https://github.com/alibaba/dragonwell8/issues/311)
=> [Wisp] Separate IO poller

src/hotspot/share/classfile/classListParser.cpp, src/hotspot/share/classfile/classListParser.hpp, src/hotspot/share/classfile/classLoaderExt.cpp, src/hotspot/share/classfile/compactHashtable.hpp, src/hotspot/share/classfile/dictionary.cpp, src/hotspot/share/classfile/moduleEntry.cpp, src/hotspot/share/classfile/packageEntry.cpp, src/hotspot/share/gc/g1/g1CodeCacheRemSet.cpp, src/hotspot/share/memory/metaspaceClosure.cpp, src/hotspot/share/memory/metaspaceClosure.hpp, src/hotspot/share/memory/metaspaceShared.cpp, src/hotspot/share/utilities/globalDefinitions.hpp, src/hotspot/share/utilities/hashtable.cpp, src/hotspot/share/utilities/hashtable.hpp, src/hotspot/share/utilities/hashtable.inline.hpp, src/hotspot/share/utilities/resourceHash.hpp, test/hotspot/jtreg/runtime/appcds/AppCDSOptions.java, test/hotspot/jtreg/runtime/appcds/LotsOfClasses.java, test/hotspot/jtreg/runtime/appcds/TestCommon.java, test/lib/jdk/test/lib/cds/CDSOptions.java, test/lib/jdk/test/lib/cds/CDSTestUtils.java
Summary: JDK-8213587 has made some hashtables resizeable, so their performance could boost a lot: on springboot-petclinic: dump time (9.2s -> 4.9s, 87% enhancement)
JBS issue: https://bugs.openjdk.org/browse/JDK-8213587
Diff: http://hg.openjdk.java.net/jdk/jdk/rev/3009ca99de32
Test Plan: all cds tests
Issue: #402
=> [Backport] JDK-8213587: Speed up CDS dump time by using resizable hashtables

test/hotspot/jtreg/runtime/appcds/TestCommon.java, test/hotspot/jtreg/runtime/appcds/customLoader/HelloCustom_JFR.java, test/hotspot/jtreg/runtime/appcds/jigsaw/modulepath/ModulePathAndCP.java, test/hotspot/jtreg/runtime/appcds/jigsaw/modulepath/ModulePathAndCP_JFR.java, test/hotspot/jtreg/runtime/appcds/jvmti/ClassFileLoadHook.java, test/hotspot/jtreg/runtime/appcds/jvmti/ClassFileLoadHookTest.java
Summary: Backport tests from JDK-8218751
Commit diff: https://github.com/openjdk/jdk/commit/d06f3e7e28bd1baf00b903a7c6b2f18965e73311
Test Plan: tests in this patch
Issue: #402
=> [Backport] Port missing tests from upstream for the JDK11 port: 8218751: Do not store original classfiles inside the CDS archive

src/hotspot/share/classfile/classLoader.cpp, src/hotspot/share/classfile/classLoader.hpp, src/hotspot/share/classfile/klassFactory.cpp, src/hotspot/share/memory/filemap.cpp, src/hotspot/share/memory/filemap.hpp
Summary: Backport 8221351 to fix some crashes.
Hg diff: https://hg.openjdk.org/jdk/jdk/rev/2221f042556d
Test Plan: CDS tests
Issue: #402
=> [Backport] 8221351: Crash in KlassFactory::check_shared_class_file_load_hook

test/hotspot/jtreg/runtime/appcds/TestCommon.java, test/hotspot/jtreg/runtime/appcds/sharedStrings/IncompatibleOptions.java
Summary: Add back missed lines in tests
Test Plan: tests in this patch, and all tests in runtime/appcds
Issue: #402
=> [Misc] Fix CDS test failures

test/hotspot/jtreg/runtime/SharedArchiveFile/NonBootLoaderClasses.java, test/hotspot/jtreg/runtime/appcds/TestCommon.java, test/hotspot/jtreg/runtime/appcds/jigsaw/modulepath/AddModules.java, test/hotspot/jtreg/runtime/appcds/jigsaw/modulepath/AddReads.java, test/hotspot/jtreg/runtime/appcds/jigsaw/modulepath/ModulePathAndCP.java, test/hotspot/jtreg/runtime/appcds/jigsaw/overridetests/OverrideTests.java
Summary: Fix multiple test failures
Commit diff: https://github.com/openjdk/jdk/commit/d06f3e7e28bd1baf00b903a7c6b2f18965e73311
Test Plan: all tests in runtime/appcds
Issue: #402
=> [Backport] 8218029: [TESTBUG] Use -Djava.class.path= to specify empty -cp in CDS tests

src/jdk.incubator.vector/share/classes/jdk/incubator/vector/AbstractVector.java, test/jdk/jdk/incubator/vector/VectorReshapeTests.java
Summary: [Backport] 8255349: Vector API issues on Big Endian
Issue: https://github.com/alibaba/dragonwell11/issues/435
=> [Backport] 8255349: Vector API issues on Big Endian

test/jdk/jdk/incubator/vector/Vector64ConversionTests.java
Summary: [Backport] 8255959: Timeouts in VectorConversion tests
Issue: https://github.com/alibaba/dragonwell11/issues/454
=> [Backport] 8255959: Timeouts in VectorConversion tests

.github/workflows/submit.yml
Summary: Add serverless-adapter build in CI
Reviewed-by: yuleil, zhengxiaolinX
Issue: #497
=> [Misc] Enable serverless-adapter build in aciton workflow

src/hotspot/share/code/location.cpp, src/hotspot/share/prims/vectorSupport.cpp, src/hotspot/share/runtime/deoptimization.cpp, src/hotspot/share/runtime/stackValue.cpp, test/jdk/jdk/incubator/vector/Vector64ConversionTests.java
Summary: Currently during deoptimization Vector's `payload` field values are restored during Vector reallocation.
But for scalar-replaced values (objects) this is not correct because that object could be re-allocated after allocation of this vector. Scalar-replaced `payload` should be restored during regular fields reassignment.
Issue: https://github.com/alibaba/dragonwell11/issues/465
=> [Backport] 8263125: During deoptimization vectors should reassign scalarized payload after all objects are reallocated.

src/hotspot/share/prims/vectorSupport.cpp
Summary: vectorIntrinsics crashes with assert(payload->is_object()) failed: expected 'object' value for scalar-replaced boxed vector but got: NULL.
It doesn't take into account the case of a scalar-replaced instance with a constant field (null in this particular case).
Reviewed-by: Zhuoren, JinZhonghui
Issue: https://github.com/alibaba/dragonwell11/issues/507
=> [Backport] 8265317: [vector] assert(payload->is_object()) failed: expected 'object' value for scalar-replaced boxed vector but got: NULL

.github/workflows/submit.yml, README.md, test/jdk/ProblemList.txt
Summary: Dragonwell has been migrated to the new org 'dragonwell-project'. We should update links to it.
Test Plan: -
Reviewed-by: D-D-H, Accelerator1996
Issue: #510
=> [Misc] Update dragonwell links to new org

.github/workflows/submit.yml
Summary: We should use an un-shaded serverless-adapter.
Test Plan: -
Reviewed-by: lingjun-cg, Accelerator1996
Issue: #345
=> [Misc] Update serverless-adapter.jar in Git Action

src/jdk.incubator.vector/share/classes/jdk/incubator/vector/VectorShape.java, test/jdk/jdk/incubator/vector/PreferredSpeciesTest.java
Summary: Vector API fails to work when MaxVectorSize is set to 0.
Test Plan: vectorapi jtreg
Reviewed-by: zhengxiaolinX, JinZhonghui, Kuaiwei
Issue: https://github.com/alibaba/dragonwell11/issues/543
=> [Backport] 8262096: Vector API fails to work due to VectorShape initialization exception

src/hotspot/share/gc/g1/g1CollectedHeap.cpp, src/hotspot/share/gc/g1/g1CollectedHeap.hpp, src/hotspot/share/gc/g1/vm_operations_g1.cpp, test/hotspot/jtreg/gc/TestMemoryMXBeansAndPoolsPresence.java, test/hotspot/jtreg/gc/g1/TestRemarkCleanupMXBean.java, test/jdk/TEST.ROOT, test/jdk/com/sun/management/GarbageCollectorMXBean/GarbageCollectionNotificationContentTest.java, test/jdk/com/sun/management/GarbageCollectorMXBean/GarbageCollectionNotificationTest.java, test/jdk/java/lang/management/MemoryMXBean/MemoryTest.java, test/jdk/java/lang/management/MemoryMXBean/MemoryTestAllGC.sh, test/lib/jdk/test/lib/jfr/GCHelper.java
Summary: Backport of 8297247
Test Plan: hotspot/jtreg:tier1-4, jdk:tier1, jdk:needs_g1gc, jdk:jdk_management, jdk:jdk_jmx, hotspot/jtreg:vmTestbase_vm_gc, hotspot/jtreg:vmTestbase_nsk_monitoring
Reviewed-by: leveretconey, D-D-H
Issue: https://github.com/dragonwell-project/dragonwell11/issues/538
=> [Backport] 8297247: Add GarbageCollectorMXBean for Remark and Cleanup pause time in G1

src/hotspot/share/logging/logOutputList.cpp, src/hotspot/share/logging/logOutputList.hpp
Solution of #529. Backport of [8288904: Incorrect memory ordering in UL](https://github.com/openjdk/jdk/pull/9225) and [8305819: LogConfigurationTest intermittently fails on AArch64](https://github.com/openjdk/jdk/pull/13421).
=> [Backport] Fix incorrect memory order in UL

src/hotspot/share/opto/callGenerator.cpp
Summary: CallGenerator::for_method_handle_inline() casts MH linker (MH::linkTo*) arguments before attempting inlining. If any argument has a speculative type attached, it is lost and can't be used later. The patch preserves speculative part while sharpening the type (if needed) based on static information from the MemberName instance.
Reviewed-by: Kuaiwei, Wangzhuo
Issue: https://github.com/dragonwell-project/dragonwell11/issues/634
=> [Backport] 8191998: C2: inlining through MH linkers drops speculative part of argument types

src/hotspot/share/opto/doCall.cpp
Summary: Once JDK-8191998 is fixed, there may be a speculative type available for the receiver. But Compile::call_generator() ignores it since there's no receiver profile available. When inlining through MethodHandle calls, C2 can improve inlining decisions by taking speculative types into account.
Reviewed-by: Kuaiwei, Wangzhuo
Issue: https://github.com/dragonwell-project/dragonwell11/issues/635
=> [Backport] 8192001: C2: inlining through dispatching MH linkers ignores speculative type of the receiver

src/hotspot/share/opto/callGenerator.cpp, test/hotspot/jtreg/compiler/types/TestMethodHandleSpeculation.java
Summary: Fix crash introduced by JDK-8191998.
Reviewed-by: Kuaiwei, Wangzhuo
Issue: https://github.com/dragonwell-project/dragonwell11/issues/636
=> [Backport] 8269285: Crash/miscompile in CallGenerator::for_method_handle_inline after JDK-8191998

src/hotspot/share/opto/bytecodeInfo.cpp, src/hotspot/share/runtime/compilationPolicy.cpp, src/hotspot/share/runtime/compilationPolicy.hpp, src/hotspot/share/runtime/globals.hpp
Summary: C2 considers absolute call site counts in its inlining decisions, which seems very wrong considering the asynchronous nature of profiling and background compilation (See InlineTree::should_inline()). It causes substantial over-inlining, which in presence of a depth-first inlining can lead to an early cut off. It also is inherently unstable. C2 already uses call frequency as an additional factor and it's better to consider only that in the inlining heuristic. The author did extensive benchmarking it yielded almost no losses and single-digit wins (up to 5%) on some benchmarks. The author think it's safe to remove/deprecate InlineFrequencyCount and continue using InlineFrequencyRatio instead. The author found that converting the frequency computation to FP and setting …
=> [Backport] 8272873: C2: Inlining should not depend on absolute call site counts

test/jdk/com/alibaba/quickstart/TestExecStartupProbe.java
Summary: As title.
Test Plan: aarch64 jtreg test
Reviewed-by: lingjun-cg, yuleil
Issue: https://github.com/dragonwell-project/dragonwell11/issues/655
=> [EagerAppCDS] extend time for testcase TestExecStartupProbe

src/hotspot/share/opto/subnode.cpp, src/hotspot/share/opto/subnode.hpp, src/hotspot/share/opto/type.hpp
Summary: In current SLP, the vectorization of Math.abs() with char type is intentionally disabled after JDK-8261022 because it generates incorrect result before.
But in Java semantics, as the char type is always non-negative, we could actually translate Math.abs(char) to a no-op by adding a no-op IR and matching rules somehow.
We can consider re-enable Math.abs() vectorization with char type.
Reviewed-by: kuaiwei, JoshuaZhuwj
Issue: https://github.com/dragonwell-project/dragonwell11/issues/648
CR: https://github.com/dragonwell-project/dragonwell11/pull/649
=> [Backport] 8276673: Optimize abs operations in C2 compiler

src/hotspot/share/opto/memnode.cpp, src/hotspot/share/opto/memnode.hpp, src/hotspot/share/opto/phaseX.cpp, test/hotspot/jtreg/compiler/escapeAnalysis/TestEliminateAllocation.java
Summary: Avoids early bailout of capturing a field store to remove unnecessary zeroing in simple methods containing only non-escaping objects.
Reviewed-by: @kuaiwei , @JoshuaZhuwj 
Issue: https://github.com/dragonwell-project/dragonwell11/issues/660
CR: https://github.com/dragonwell-project/dragonwell11/pull/661
=> [Backport] 8231412: C2: InitializeNode::detect_init_independence() bails out on simple IR shapes

src/hotspot/share/opto/graphKit.cpp
Summary: Skip copy Region node when look for last allocation
Reviewed-by: @kuaiwei , @JoshuaZhuwj 
Issue: https://github.com/dragonwell-project/dragonwell11/issues/658
CR: https://github.com/dragonwell-project/dragonwell11/pull/659
=> [Backport] 8210853: JIT: C2 doesn't skip post barrier for new allocated objects

src/hotspot/cpu/aarch64/aarch64.ad, src/hotspot/cpu/aarch64/icBuffer_aarch64.cpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.hpp, src/hotspot/share/code/codeCache.cpp, src/hotspot/share/code/codeCache.hpp, test/hotspot/jtreg/compiler/c2/aarch64/TestFarJump.java
Backport 8280872 to improve code cache density
=> [Backport] 8280872: Reorder code cache segments to improve code density

src/hotspot/os/linux/os_linux.cpp, src/hotspot/os/linux/os_linux.hpp, src/hotspot/share/services/heapDumper.cpp, src/hotspot/share/services/heapDumperCompression.hpp
This patch reduces ~16%(24s->20s) pahse 2 merge time during dumping 32g heap with 96threads.
You might argue why this is Linux-only optimization, because sendfile requires at least one socket fd in other platforms([aix sendfile](https://www.ibm.com/docs/en/aix/7.1?topic=s-send-file-subroutine) [maxos sendfile](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sendfile.2.html) [win32 TransmitFile](https://learn.microsoft.com/en-us/windows/win32/api/mswsock/nf-mswsock-transmitfile)), while [only Linux](https://man7.org/linux/man-pages/man2/sendfile.2.html) supports both two file descriptors.
=> HeapDump: Optimize segmented heap file merging phase

.github/workflows/check_pr.yml
Summary: Since the environment provided by github always runs out of space, the environment needs to be updated.
Test Plan: CI
Reviewed-by: sendaoYan, yuleil
Issue: https://github.com/dragonwell-project/dragonwell11/issues/674
=> [Misc] Update riscv build environment

src/hotspot/share/opto/c2_CodeStubs.hpp
Summary: Fix jtreg nightly failure due to backport 8291555.
Reviewed-by: kuaiwei,yifeng
Issue: https://github.com/dragonwell-project/dragonwell11/issues/685
=> [Backport] C2CodeStubList should be ResourceObj

test/jdk/com/alibaba/quickstart/StartupProbeTestRunner.java, test/jdk/com/alibaba/quickstart/TestExecStartupProbe.java
Summary: Change hard-code sleep time to test if a file exist which means CDS dump successful.
Test Plan: TestExecStartupProbe.java
Reviewed-by: jia-wei-tang, yuleil
Issue: https://github.com/dragonwell-project/dragonwell11/issues/687
=> [EagerAppCDS] Fix unstable test case TestExecStartupProbe

src/hotspot/share/runtime/arguments.cpp, src/hotspot/share/runtime/synchronizer.cpp
Summary: missing log of monitor inflation
Reviewed-by: yulei, ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/679
=> [Backport] Missing monitor inflation log

src/hotspot/share/gc/g1/g1OopClosures.inline.hpp, src/hotspot/share/gc/g1/g1ParScanThreadState.cpp, src/hotspot/share/gc/g1/g1ParScanThreadState.inline.hpp, src/hotspot/share/gc/parallel/psPromotionManager.cpp, src/hotspot/share/oops/markOop.hpp, src/hotspot/share/oops/oop.hpp, src/hotspot/share/oops/oop.inline.hpp, src/hotspot/share/runtime/arguments.cpp, test/hotspot/gtest/gc/shared/test_preservedMarks.cpp, test/hotspot/gtest/gc/shared/test_slidingForwarding.cpp
Summary: Alternative self-forwarding mechanism under flag UseAltGCForwarding.
Now support G1 and parallelGC.
Add missing gtest of UseAltGCForwarding from 8305896.
Reviewed-by: yude.lin, yifeng.jin
Issue: https://github.com/dragonwell-project/dragonwell11/issues/692
=> [Backport] 8305898: Alternative self-forwarding mechanism

src/hotspot/cpu/aarch64/c2_CodeStubs_aarch64.cpp, src/hotspot/cpu/aarch64/sharedRuntime_aarch64.cpp, src/hotspot/cpu/x86/c2_CodeStubs_x86.cpp, src/hotspot/cpu/x86/sharedRuntime_x86_64.cpp, src/hotspot/share/runtime/coroutine.cpp, src/hotspot/share/runtime/coroutine.hpp, src/hotspot/share/runtime/objectMonitor.inline.hpp, src/hotspot/share/runtime/synchronizer.cpp, test/hotspot/jtreg/runtime/coroutine/TestWisp2Switch.java, test/hotspot/jtreg/runtime/coroutine/TestWisp2Switch2.java
Summary: Wisp should support the new fast locking from backport of 8291555
Reviewed-by: kuaiwei, yulei, ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/697
=> [Wisp] Support new fast locking from backport of 8291555

src/hotspot/share/jfr/leakprofiler/chains/edgeStore.cpp, src/hotspot/share/jfr/leakprofiler/chains/edgeStore.hpp, src/hotspot/share/jfr/leakprofiler/checkpoint/eventEmitter.cpp
Summary: Prepare Leak Profiler for Lilliput
Reviewed-by: ddh, yanglong
Issue: https://github.com/dragonwell-project/dragonwell11/issues/704
=> [Backport] 8275415: Prepare Leak Profiler for Lilliput

src/hotspot/share/jfr/leakprofiler/chains/edgeStore.cpp
Summary: Fix windwos build failure from backport of 8275415
Reviewed-by: ddh, yanglong
Issue: https://github.com/dragonwell-project/dragonwell11/issues/704
=> [Backport] Fix windows build failure

test/jdk/com/alibaba/cds/TestSuperClassNotExist.java
Summary: If the source is null, the EagerAppCDS dump failed.
Test Plan: All CDS testcases.
Reviewed-by: yulei, tangjiawei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/710
=> [EagerAppCDS] Add a EagerAppCDS testcase that test when source is null

src/hotspot/share/services/heapDumper.cpp, test/hotspot/jtreg/serviceability/dcmd/gc/HeapDumpParallelTest.java
Summary: Segment file is closed from DumpWriter dtor. On Unix systems remove can delete an opened file, on Windows it fails with "access denied". The fix destroys DumpWriter objects for segment files after all data are dumped
Test Plan: HeapDumpParallelTest.java
Reviewed-by: D-D-H, yuleil
Issue: #714
=> [Backport] 8319053: Segment dump files remain after parallel heap dump on Windows

src/hotspot/share/runtime/synchronizer.cpp
Summary: Fix new fast-locking is_lock_owned.
Reviewed-by: yulei, ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/679
=> [Backport] Fix new fast-locking is_lock_owned of backport of 8291555

src/hotspot/cpu/aarch64/c1_LIRAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/c1_MacroAssembler_aarch64.cpp, src/hotspot/cpu/x86/c1_LIRAssembler_x86.cpp, src/hotspot/cpu/x86/c1_MacroAssembler_x86.cpp, src/hotspot/share/gc/parallel/mutableNUMASpace.cpp, src/hotspot/share/gc/parallel/psPromotionLAB.cpp, src/hotspot/share/gc/shared/collectedHeap.cpp, src/hotspot/share/gc/shared/memAllocator.cpp, src/hotspot/share/gc/shared/plab.cpp, src/hotspot/share/gc/shared/space.cpp, src/hotspot/share/gc/shared/threadLocalAllocBuffer.hpp, src/hotspot/share/oops/arrayOop.hpp, src/hotspot/share/oops/objArrayOop.hpp, src/hotspot/share/oops/oop.inline.hpp, src/hotspot/share/opto/runtime.cpp, src/hotspot/share/opto/type.cpp, src/hotspot/share/prims/unsafe.cpp, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/memory/Universe.java, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/oops/Array.java, test/hotspot/gtest/oops/test_arrayOop.cpp, test/hotspot/gtest/oops/test_objArrayOop.cpp, test/hotspot/jtreg/gtest/ArrayTests.java, test/hotspot/jtreg/gtest/ObjArrayTests.java, test/hotspot/jtreg/runtime/FieldLayout/ArrayBaseOffsets.java, test/hotspot/jtreg/runtime/FieldLayout/BaseOffsets.java
Summary: With compact object headers, there is always a 32-bit gap between length and first element. Fill the gap only with UseCompactObjectHeaders.
Testing: CICD
Reviewers: yulei, ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/727
=> [Backport] 8139457: Relax alignment of array elements

test/hotspot/jtreg/runtime/eagerappcds/TestClassLoaderWithJVMTIAgent.java, test/jdk/com/alibaba/cds/Classes4CDS.java, test/jdk/com/alibaba/cds/TestDumpAndLoadClass.java, test/jdk/com/alibaba/cds/TestDumpAndLoadClassWithDifferentCP.java, test/jdk/com/alibaba/cds/TestDumpAndLoadClassWithException.java, test/jdk/com/alibaba/cds/TestDumpAndLoadClassWithNullURL.java, test/jdk/com/alibaba/cds/TestDumpAndLoadClassWithWisp.java, test/jdk/com/alibaba/cds/TestDumpAndLoadNotFound.java, test/jdk/com/alibaba/cds/TestDumpAndLoadVerficationFailure.java, test/jdk/com/alibaba/cds/TestDumpListInParallel.java, test/jdk/com/alibaba/cds/TestDumpUnsupportedCheck.java, test/jdk/com/alibaba/cds/TestLoadClassFlow.java, test/jdk/com/alibaba/cds/TestWispWithAppCDS.java, test/jdk/com/alibaba/quickstart/TestMultiVersionedJar.java
Summary: Since upstream delete `createJavaProcessBuilder`, those testcases need to call another functions to replace it.
Testing:
com/alibaba/cds/TestDumpAndLoadClass.java
com/alibaba/cds/TestDumpAndLoadClassWithDifferentCP.java com/alibaba/cds/TestDumpAndLoadClassWithException.java com/alibaba/cds/TestDumpAndLoadClassWithNullURL.java com/alibaba/cds/TestDumpAndLoadClassWithWisp.java
com/alibaba/cds/TestDumpAndLoadNotFound.java
com/alibaba/cds/TestDumpAndLoadVerficationFailure.java com/alibaba/cds/TestDumpListInParallel.java
com/alibaba/cds/TestDumpUnsupportedCheck.java
com/alibaba/cds/TestLoadClassFlow.java
com/alibaba/cds/TestWispWithAppCDS.java
runtime/eagerappcds/TestClassLoaderWithJVMTIAgent.java com/alibaba/quickstart/TestMultiVersionedJar.java
Reviewers: lingjun-cg, yulei
Issue: …
=> [EagerAppCDS] fix compile bugs in testcase

src/hotspot/os/linux/globals_linux.hpp, src/hotspot/os/linux/os_linux.cpp, src/hotspot/share/code/codeCache.cpp, src/hotspot/share/code/codeCache.hpp, src/hotspot/share/runtime/java.cpp, src/hotspot/share/services/diagnosticCommand.cpp, src/hotspot/share/services/diagnosticCommand.hpp, test/hotspot/jtreg/serviceability/dcmd/compiler/PerfMapTest.java
Summary: Support dumping text file format describing the mapping between address ranges and Java symbol names for Linux perf tool. There are two ways to trigger dumping:
1. Launch java application with option -XX:+DumpPerfMapAtExit, the file will be generated automatically when application exits.
2. Use command 'jcmd <pid> Compiler.perfmap' to trigger dump during application running.
Testing: test/hotspot/jtreg/serviceability/dcmd/compiler/PerfMapTest.java
Reviewers: kuaiwei.kw, denghui.ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/744
=> [Backport] 8254723: add diagnostic command to write Linux perf map file

src/hotspot/share/gc/g1/c2/g1BarrierSetC2.cpp, test/hotspot/jtreg/compiler/c2/aarch64/TestVolatiles.java
1. Backport JDK-8225776 to Optimize branch frequency of G1's write post-barrier in C2
2. Backport JDK-8232828 to fix testcase fails after JDK-8225776
=> [Backport] 8225776: Optimize branch frequency of G1's write post-barrier in C2

src/hotspot/cpu/aarch64/assembler_aarch64.hpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp, src/hotspot/cpu/aarch64/macroAssembler_aarch64.hpp, src/hotspot/cpu/aarch64/vtableStubs_aarch64.cpp
Minor conflicts:
1 conflict in src/hotspot/cpu/aarch64/assembler_aarch64.hpp:
tip: guarantee(ext().shift() <= 0 || ext().shift() == (int)size, "bad shift"); 
dw11: guarantee(_ext.shift() <= 0 || _ext.shift() == (int)size, "bad shift");
3 conflicts in src/hotspot/cpu/aarch64/macroAssembler_aarch64.cpp similar to:
tip: int ioffset = in_bytes(itableOffsetEntry::interface_offset());
dw11: int ioffset = itableOffsetEntry::interface_offset_in_bytes();
Summary: Improve performance of itable stub on aarch64
Test Plan: hotspot/jtreg
Reviewed-by: kuaiwei, sandlerwang
Issue: https://github.com/dragonwell-project/dragonwell11/issues/763
=> [Backport] 8307352: AARCH64: Improve itable_stub

src/hotspot/share/c1/c1_GraphBuilder.cpp, src/hotspot/share/ci/bcEscapeAnalyzer.cpp, src/hotspot/share/ci/ciInstanceKlass.hpp, src/hotspot/share/ci/ciMethod.cpp, src/hotspot/share/ci/ciMethod.hpp, src/hotspot/share/ci/ciStreams.cpp, src/hotspot/share/code/codeCache.cpp, src/hotspot/share/code/dependencies.cpp, src/hotspot/share/code/dependencies.hpp, src/hotspot/share/oops/instanceKlass.cpp, src/hotspot/share/oops/instanceKlass.hpp, src/hotspot/share/oops/method.cpp, src/hotspot/share/oops/method.hpp, src/hotspot/share/opto/callGenerator.cpp, src/hotspot/share/opto/callGenerator.hpp, src/hotspot/share/opto/compile.hpp, src/hotspot/share/opto/doCall.cpp, src/hotspot/share/opto/graphKit.cpp, src/hotspot/share/opto/graphKit.hpp, src/hotspot/share/runtime/globals.hpp, test/hotspot/jtreg/compiler/cha/AbstractRootMethod.java, test/hotspot/jtreg/compiler/cha/DefaultRootMethod.java, test/hotspot/jtreg/compiler/cha/StrengthReduceInterfaceCall.java, test/hotspot/jtreg/compiler/cha/Utils.java
With this backport, interface call could be inlined if there is only one implementation of the invoked method after class hierarchy analysis, as shown in the following case.
```
interface I1 {
public int m();
}
abstract class C1 implements I1 {}
class C2 extends C1 {
public int m() {
return 0;
}
}
class Test {
public static void main(String[] args) {
run(new C2());
}
public static void run(C1 c1) {
c1.m(); // will inline C2.m because only class C2 implements method m after Class Hierarchy Analysis
}
}
```
benchmark: renaissance 
platform: x86
config:4C8G
benchmark: renaissance
platform: aarch64
config:4C8G
There isn't any change for SPECjbb on x86 and aarch64 platform.
[6986483](https://github.com/openjdk/jdk/commit/ac3711e9cd4b06853619db82025f55cfc9f2712d)CHA: optimize calls through …
=> [Backport] CHA inline

src/hotspot/share/runtime/globals.hpp
Summary: Disable CHA inline by default, could be enabled by option -XX:+UnlockDiagnosticVMOptions -XX:+UseVtableBasedCHA
Testing: jtreg
Reviewers: kuaiwei.kw, maoliang.ml
Issue: https://github.com/dragonwell-project/dragonwell11/issues/774
=> [JIT] Disable UseVtableBasedCHA by default

test/jdk/com/sun/management/GarbageCollectorMXBean/GarbageCollectionNotificationContentTest.java
Summary: G1 Concurrent GC only monitors G1 Old Gen
Testing: hotspot/jtreg
Issue: https://github.com/dragonwell-project/dragonwell11/issues/790
=> [GC] Fix a test failure on G1 Concurrent GC MXBean

test/hotspot/jtreg/runtime/FieldLayout/ArrayBaseOffsets.java
Summary: Disable runtime/FieldLayout/ArrayBaseOffsets.java#no-coh-no-ccp and runtime/FieldLayout/ArrayBaseOffsets.java#no-coh-with-ccp when test with -XX:+UseCompactObjectHeaders
Reviewers: maoliang.ml, lvfei.lv
Issue: https://github.com/dragonwell-project/dragonwell11/issues/812
=> [Misc] Disable ArrayBaseOffsets.java#no-coh-no-ccp when test with -XX:+UseCompactObjectHeaders

test/hotspot/jtreg/runtime/FieldLayout/ArrayBaseOffsets.java
Summary: alignment of array elements hasn't changed on riscv64, thus skip its test
Testing: test/hotspot/jtreg/runtime/FieldLayout/ArrayBaseOffsets.java
Reviewers: mmyxym, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell11/issues/814
=> [GC] Disable ArrayBaseOffsets.java on riscv64

src/hotspot/cpu/riscv/nativeInst_riscv.hpp, src/hotspot/cpu/riscv/vtableStubs_riscv.cpp
Summary: Clean backport of JDK-8290496, this backport has been merged to riscv-port-jdk11u
Reviewers: kuaiwei.kw, xingqizheng.xqz
Issue: https://github.com/dragonwell-project/dragonwell11/issues/818
待办事项：
=> [Backport] 8290496: riscv: Fix build warnings-as-errors with GCC 11

src/hotspot/share/gc/parallel/psPromotionManager.hpp, src/hotspot/share/gc/parallel/psPromotionManager.inline.hpp
After port [JDK-8246718](https://bugs.openjdk.org/browse/JDK-8246718) form JDK15, the critical-jOPS of SPECjbb has a nearly 8% improvement on g8a and g8i with a configuration of 8 cores and 16G memory, while max-jOPS was not seen evident changes. Also both the max-jOPS and critical-jOPS have no significant differences on g8y.
And those test results are basically similar with [JDK-8246718](https://bugs.openjdk.org/browse/JDK-8246718)
=> [Backport] 8246718: ParallelGC should not check for forward objects for copy task queue

.github/workflows/build-linux.yml, .github/workflows/build-riscv.yml, .github/workflows/main.yml
Summary: reduce arm runner permissions and update actions config
Testing: CI pipline
Reviewers: lei.yul, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell11/issues/840
=> [Misc] Reduce runner permissions

src/hotspot/share/code/nmethod.cpp, src/hotspot/share/code/nmethod.hpp, src/hotspot/share/runtime/globals_ext.hpp, src/hotspot/share/runtime/vmStructs.cpp, src/jdk.hotspot.agent/share/classes/sun/jvm/hotspot/code/NMethod.java
Summary: Add option ReduceNMethodSize. If enable, jvm will move
immutable nmethod data out of CodeCache
Testing: CI testing
Reviewers: yueshi.zwj, lusou.zq
Issue: https://github.com/dragonwell-project/dragonwell11/issues/842
=> [JIT] Backport: 8331087: Move immutable nmethod data from CodeCache

src/hotspot/share/gc/parallel/parallelArguments.cpp, src/hotspot/share/gc/parallel/parallel_globals.hpp, src/hotspot/share/gc/parallel/psAdaptiveSizePolicy.cpp, src/hotspot/share/gc/parallel/psAdaptiveSizePolicy.hpp
Summary: add new parallel gc option UseIOPrioritySizePolicy to early shrink heap when io wait is high.
Testing: jtreg
Reviewers: maoliang.ml, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell11/issues/846
CR: https://github.com/dragonwell-project/dragonwell11/pull/847
=> [GC] Add IO related size policy for Parallel GC

src/hotspot/share/gc/parallel/parallel_globals.hpp
Summary: change type from float to uint for IOPrioritySizePolicyEdenScale to avoid build failure on aarch64
Testing: jtreg
Reviewers: maoliang.ml, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell11/issues/
CR: https://github.com/dragonwell-project/dragonwell11/pull/
=> [GC] Fix option type in IOPrioritySizePolicy

src/hotspot/share/gc/g1/g1CollectedHeap.cpp
Summary: Since
https://github.com/dragonwell-project/dragonwell11/commit/d4c08314a2cc2f44d157c40a5b4b5215af76d78c some cleanup tasks might be skipped in UseCompactObjectHeaders. We should fix related assertions.
Testing: hotspot/jtreg
Reviewers: mmyxym, weixlu
Issue: https://github.com/dragonwell-project/dragonwell11/issues/850
=> [GC] Fix an assertion that assumed ICBuffer should be cleaned

src/hotspot/share/gc/parallel/psAdaptiveSizePolicy.cpp
Summary: use SIZE_FORMAT to avoid build failure on windows
Testing: jtreg
Reviewers: maoliang.ml, yude.lyd
Issue: https://github.com/dragonwell-project/dragonwell11/issues/
=> [GC] Fix data type in IOPrioritySizePolicy

src/hotspot/share/runtime/arguments.cpp, src/hotspot/share/runtime/globals_ext.hpp, src/java.base/share/classes/java/math/BigDecimal.java, test/jdk/java/math/BigDecimal/StrippingTailZerosTest.java
Summary: Use binary search in zero stripping of BigDecimal.divide
Testing: jtreg
Reviewers:
Issue: https://github.com/dragonwell-project/dragonwell11/issues/848
=> [Misc] optimize BigDecimal.divide

.github/actions/get-jtreg/action.yml
Summary: CICD
Testing: CI pipline
Reviewers: lei.yul, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell11/issues/858
=> [Misc] Build Jtreg using JDK on aach64 runners

src/hotspot/share/code/nmethod.cpp
Summary: free immutable data in nmethod::flush
Testing: test/hotspot/jtreg/compiler/codecache/stress/UnexpectedDeoptimizationTest.java
Reviewers: lusou.zq, yueshi.zwj
Issue: https://github.com/dragonwell-project/dragonwell11/issues/861
=> [JIT] Fix mem leak for ReduceNMethodSize

src/hotspot/cpu/riscv/riscv.ad
Summary: backport JDK-8301313 to fix native build Internal Error matcher.cpp:1632 assert(false) failed: bad AD file
Reviewers: MaxXSoft, kuaiwei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/865
Additional testing:
=> [Backport] 8301313: RISC-V: C2: assert(false) failed: bad AD file due to missing match rule

.github/actions/build-additional-components/action.yml, .github/workflows/build-linux.yml
Summary: as title
Testing: CICD
Reviewers: denghui.ddh,lingjun.cg
Issue: https://github.com/dragonwell-project/dragonwell11/issues/870
=> [Misc] Add criu in built jdk

test/lib/jdk/test/lib/containers/docker/DockerTestUtils.java
Summary: A previous CRaC pactch change the signature of DockerTestUtils.buildJdkContainerImage(String imageName).All testcases depend on docker build will compile failed.
Testing: TestMemoryWithCgroupV1.java
Reviewed-by: yansendao.ysd,lvfei.lv
Issue: https://github.com/dragonwell-project/dragonwell11/issues/872
=> [Misc] Fix testcase that depend on docker build

src/java.base/share/native/launcher/main.c
Summary: There no __SIGRTMIN macro in Alpine Linux
Testing: All CRaC testcases.
Reviewers: Accelerator1996, denghui.ddh
Issue: https://github.com/dragonwell-project/dragonwell11/issues/883
=> [Runtime] CRaC: fix compile error in Alpine Linux

test/jdk/tools/jar/modularJar/Basic.java
Summary: Backport JDK-8216539 to fix tools/jar/modularJar/Basic.java intermittent fails
Reviewers: Accelerator1996, ziyilin
Issue: https://github.com/dragonwell-project/dragonwell11/issues/908
=> [Misc] Backport JDK-8216539 to fix Basic.java intermittent fails

src/hotspot/share/ci/ciMethodData.cpp, src/hotspot/share/ci/ciMethodData.hpp, src/hotspot/share/oops/methodData.cpp, src/hotspot/share/oops/methodData.hpp
Summary: 8257919: [JVMCI] profiling info didn't change after reprofile Reviewers: kuaiwei, wenjie
Testings: jtreg
Issue: https://bugs.openjdk.org/browse/JDK-8257919,
https://github.com/dragonwell-project/dragonwell11/issues/903
=> [Backport]: 8257919: [JVMCI] profiling info didn't change after reprofile

test/lib/jdk/test/lib/apps/LingeredApp.java
Summary: LingeredApp is started without jtreg's vm options. It will lead to testing error due to inconsistent vm options for dumping cds and applying cds.
Reviewer: raodao, lvfei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/904
=> [Misc] Take VMoptions set in jtreg to LingeredApp

src/hotspot/share/gc/shenandoah/c2/shenandoahSupport.cpp, src/hotspot/share/opto/castnode.cpp, src/hotspot/share/opto/castnode.hpp, src/hotspot/share/opto/compile.cpp, src/hotspot/share/opto/compile.hpp, src/hotspot/share/opto/convertnode.cpp, src/hotspot/share/opto/loopnode.cpp, src/hotspot/share/opto/loopnode.hpp, src/hotspot/share/opto/node.cpp, src/hotspot/share/opto/node.hpp, src/hotspot/share/opto/opaquenode.cpp, src/hotspot/share/opto/opaquenode.hpp, src/hotspot/share/opto/phaseX.cpp, src/hotspot/share/runtime/vmStructs.cpp, test/hotspot/jtreg/gc/shenandoah/compiler/TestBarrierExpansionDeadMemPhi.java
[Backport] 8255000: C2: Unify IGVN processing when loop opts are over
Summary: it include 3 patches
8255000: C2: Unify IGVN processing when loop opts are over
8255400: Shenandoah: C2 failures after JDK-8255000
8255120: C2: assert(outer->outcnt() >= phis + 2 && outer->outcnt() <= phis + 2 + stores + 1) failed: only phis
Testing: CICD
Reviewers: wangzhuo, yueshi.zwj
Issue: https://github.com/dragonwell-project/dragonwell11/issues/915
=> [Backport] 8255000: C2: Unify IGVN processing when loop opts are over

test/jdk/com/alibaba/wisp/bug/TestCancelTimerAndSleep.java
Summary: as title
Testing: com/alibaba/wisp/bug/TestCancelTimerAndSleep.java
Reviewers: ziyilin, yulei
Issue: https://github.com/dragonwell-project/dragonwell11/issues/901
=> [Wisp] prevent running time-related case in debug mode

.github/actions/do-build/action.yml, .github/actions/get-bundles/action.yml, .github/actions/upload-bundles/action.yml, .github/workflows/test.yml
Summary: gha failed because it uses a deprecated version
Testing: CI
Reviewers: jia-wei-tang, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell11/issues/932
=> [Misc] update version of upload-artifact in gha

src/hotspot/share/runtime/vmStructs.cpp
Summary: provide Deoptimization::Reason_polymorphic in vmStructs, this is to fix test TestPrintMdo.java and ClhsdbCDSCore.java
Testing: jtreg and ci
Reviewers: maoliang, yy
Issue: https://github.com/dragonwell-project/dragonwell11/issues/936
=> [JIT] expose polymorphic deoptimize reason

src/hotspot/share/runtime/thread.cpp, test/jdk/com/alibaba/wisp2/TestWispThreadInfo.java
Summary: The current_coroutine may be null.
Testing: TestWispThreadInfo.java
Reviewers: lingjun.cg, yulei.lx
Issue: https://github.com/dragonwell-project/dragonwell11/issues/930
=> [Wisp] fix get_thread_stat for wisp thread

src/java.base/linux/classes/com/alibaba/wisp/engine/WispEngine.java
Summary: The daemonThreadGroup should not be inited when wisp is off.
Testing: test/jdk/java/lang/ThreadGroup/NullThreadName.java
Reviewers: yulei.lx, lingjun.cg
Issue: https://github.com/dragonwell-project/dragonwell11/issues/941
=> [Wisp] thread leak when wisp off

.github/workflows/main.yml
Summary: These two patches in JDK 11 were supposed to be merged into Dragonwell, but they were accidentally left out.
Testing: CI/CD
Reviewers: Accelerator1996, sendaoYan
Issue: https://github.com/dragonwell-project/dragonwell11/issues/944
=> [Misc] Backport JDK-8336928 and JDK-8338402 to fix CI

test/jdk/java/net/CookieHandler/B6644726.java
[Misc] Backport JDK-8365811 to fix test/jdk/java/net/CookieHandler/B6644726.java failure
Backport-of: b453eb63c641e1e69b4aef57a220ebe45b9d1693 (cherry picked from commit e0fd1f9ad6b745f65e93d22938ec5c19843323b3)
=> [Misc] Backport JDK-8365811 to fix test/jdk/java/net/CookieHandler/B6644726.java failure
